//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:2.0.50727.3623
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Toyz4net.Core.TraditionalSimplifiedWebService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://webxml.com.cn/", ConfigurationName="TraditionalSimplifiedWebService.TraditionalSimplifiedWebServiceSoap")]
    public interface TraditionalSimplifiedWebServiceSoap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://webxml.com.cn/toSimplifiedChinese", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        string toSimplifiedChinese(string sText);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://webxml.com.cn/toTraditionalChinese", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        string toTraditionalChinese(string sText);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    public interface TraditionalSimplifiedWebServiceSoapChannel : Toyz4net.Core.TraditionalSimplifiedWebService.TraditionalSimplifiedWebServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    public partial class TraditionalSimplifiedWebServiceSoapClient : System.ServiceModel.ClientBase<Toyz4net.Core.TraditionalSimplifiedWebService.TraditionalSimplifiedWebServiceSoap>, Toyz4net.Core.TraditionalSimplifiedWebService.TraditionalSimplifiedWebServiceSoap {
        
        public TraditionalSimplifiedWebServiceSoapClient() {
        }
        
        public TraditionalSimplifiedWebServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public TraditionalSimplifiedWebServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public TraditionalSimplifiedWebServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public TraditionalSimplifiedWebServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string toSimplifiedChinese(string sText) {
            return base.Channel.toSimplifiedChinese(sText);
        }
        
        public string toTraditionalChinese(string sText) {
            return base.Channel.toTraditionalChinese(sText);
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://webxml.com.cn/", ConfigurationName="TraditionalSimplifiedWebService.TraditionalSimplifiedWebServiceHttpGet")]
    public interface TraditionalSimplifiedWebServiceHttpGet {
        
        // CODEGEN: 操作 toSimplifiedChinese 以后生成的消息协定不是 RPC，也不是换行文档。
        [System.ServiceModel.OperationContractAttribute(Action="http://webxml.com.cn/TraditionalSimplifiedWebServiceHttpGet/toSimplifiedChineseRe" +
            "quest", ReplyAction="http://webxml.com.cn/TraditionalSimplifiedWebServiceHttpGet/toSimplifiedChineseRe" +
            "sponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        Toyz4net.Core.TraditionalSimplifiedWebService.toSimplifiedChineseResponse toSimplifiedChinese(Toyz4net.Core.TraditionalSimplifiedWebService.toSimplifiedChineseRequest request);
        
        // CODEGEN: 操作 toTraditionalChinese 以后生成的消息协定不是 RPC，也不是换行文档。
        [System.ServiceModel.OperationContractAttribute(Action="http://webxml.com.cn/TraditionalSimplifiedWebServiceHttpGet/toTraditionalChineseR" +
            "equest", ReplyAction="http://webxml.com.cn/TraditionalSimplifiedWebServiceHttpGet/toTraditionalChineseR" +
            "esponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        Toyz4net.Core.TraditionalSimplifiedWebService.toTraditionalChineseResponse toTraditionalChinese(Toyz4net.Core.TraditionalSimplifiedWebService.toTraditionalChineseRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class toSimplifiedChineseRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string sText;
        
        public toSimplifiedChineseRequest() {
        }
        
        public toSimplifiedChineseRequest(string sText) {
            this.sText = sText;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class toSimplifiedChineseResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://webxml.com.cn/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string @string;
        
        public toSimplifiedChineseResponse() {
        }
        
        public toSimplifiedChineseResponse(string @string) {
            this.@string = @string;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class toTraditionalChineseRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string sText;
        
        public toTraditionalChineseRequest() {
        }
        
        public toTraditionalChineseRequest(string sText) {
            this.sText = sText;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class toTraditionalChineseResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://webxml.com.cn/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string @string;
        
        public toTraditionalChineseResponse() {
        }
        
        public toTraditionalChineseResponse(string @string) {
            this.@string = @string;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    public interface TraditionalSimplifiedWebServiceHttpGetChannel : Toyz4net.Core.TraditionalSimplifiedWebService.TraditionalSimplifiedWebServiceHttpGet, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    public partial class TraditionalSimplifiedWebServiceHttpGetClient : System.ServiceModel.ClientBase<Toyz4net.Core.TraditionalSimplifiedWebService.TraditionalSimplifiedWebServiceHttpGet>, Toyz4net.Core.TraditionalSimplifiedWebService.TraditionalSimplifiedWebServiceHttpGet {
        
        public TraditionalSimplifiedWebServiceHttpGetClient() {
        }
        
        public TraditionalSimplifiedWebServiceHttpGetClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public TraditionalSimplifiedWebServiceHttpGetClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public TraditionalSimplifiedWebServiceHttpGetClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public TraditionalSimplifiedWebServiceHttpGetClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Toyz4net.Core.TraditionalSimplifiedWebService.toSimplifiedChineseResponse Toyz4net.Core.TraditionalSimplifiedWebService.TraditionalSimplifiedWebServiceHttpGet.toSimplifiedChinese(Toyz4net.Core.TraditionalSimplifiedWebService.toSimplifiedChineseRequest request) {
            return base.Channel.toSimplifiedChinese(request);
        }
        
        public string toSimplifiedChinese(string sText) {
            Toyz4net.Core.TraditionalSimplifiedWebService.toSimplifiedChineseRequest inValue = new Toyz4net.Core.TraditionalSimplifiedWebService.toSimplifiedChineseRequest();
            inValue.sText = sText;
            Toyz4net.Core.TraditionalSimplifiedWebService.toSimplifiedChineseResponse retVal = ((Toyz4net.Core.TraditionalSimplifiedWebService.TraditionalSimplifiedWebServiceHttpGet)(this)).toSimplifiedChinese(inValue);
            return retVal.@string;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Toyz4net.Core.TraditionalSimplifiedWebService.toTraditionalChineseResponse Toyz4net.Core.TraditionalSimplifiedWebService.TraditionalSimplifiedWebServiceHttpGet.toTraditionalChinese(Toyz4net.Core.TraditionalSimplifiedWebService.toTraditionalChineseRequest request) {
            return base.Channel.toTraditionalChinese(request);
        }
        
        public string toTraditionalChinese(string sText) {
            Toyz4net.Core.TraditionalSimplifiedWebService.toTraditionalChineseRequest inValue = new Toyz4net.Core.TraditionalSimplifiedWebService.toTraditionalChineseRequest();
            inValue.sText = sText;
            Toyz4net.Core.TraditionalSimplifiedWebService.toTraditionalChineseResponse retVal = ((Toyz4net.Core.TraditionalSimplifiedWebService.TraditionalSimplifiedWebServiceHttpGet)(this)).toTraditionalChinese(inValue);
            return retVal.@string;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://webxml.com.cn/", ConfigurationName="TraditionalSimplifiedWebService.TraditionalSimplifiedWebServiceHttpPost")]
    public interface TraditionalSimplifiedWebServiceHttpPost {
        
        // CODEGEN: 操作 toSimplifiedChinese 以后生成的消息协定不是 RPC，也不是换行文档。
        [System.ServiceModel.OperationContractAttribute(Action="http://webxml.com.cn/TraditionalSimplifiedWebServiceHttpPost/toSimplifiedChineseR" +
            "equest", ReplyAction="http://webxml.com.cn/TraditionalSimplifiedWebServiceHttpPost/toSimplifiedChineseR" +
            "esponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        Toyz4net.Core.TraditionalSimplifiedWebService.toSimplifiedChineseResponse1 toSimplifiedChinese(Toyz4net.Core.TraditionalSimplifiedWebService.toSimplifiedChineseRequest1 request);
        
        // CODEGEN: 操作 toTraditionalChinese 以后生成的消息协定不是 RPC，也不是换行文档。
        [System.ServiceModel.OperationContractAttribute(Action="http://webxml.com.cn/TraditionalSimplifiedWebServiceHttpPost/toTraditionalChinese" +
            "Request", ReplyAction="http://webxml.com.cn/TraditionalSimplifiedWebServiceHttpPost/toTraditionalChinese" +
            "Response")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        Toyz4net.Core.TraditionalSimplifiedWebService.toTraditionalChineseResponse1 toTraditionalChinese(Toyz4net.Core.TraditionalSimplifiedWebService.toTraditionalChineseRequest1 request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class toSimplifiedChineseRequest1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string sText;
        
        public toSimplifiedChineseRequest1() {
        }
        
        public toSimplifiedChineseRequest1(string sText) {
            this.sText = sText;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class toSimplifiedChineseResponse1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://webxml.com.cn/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string @string;
        
        public toSimplifiedChineseResponse1() {
        }
        
        public toSimplifiedChineseResponse1(string @string) {
            this.@string = @string;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class toTraditionalChineseRequest1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string sText;
        
        public toTraditionalChineseRequest1() {
        }
        
        public toTraditionalChineseRequest1(string sText) {
            this.sText = sText;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class toTraditionalChineseResponse1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://webxml.com.cn/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string @string;
        
        public toTraditionalChineseResponse1() {
        }
        
        public toTraditionalChineseResponse1(string @string) {
            this.@string = @string;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    public interface TraditionalSimplifiedWebServiceHttpPostChannel : Toyz4net.Core.TraditionalSimplifiedWebService.TraditionalSimplifiedWebServiceHttpPost, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    public partial class TraditionalSimplifiedWebServiceHttpPostClient : System.ServiceModel.ClientBase<Toyz4net.Core.TraditionalSimplifiedWebService.TraditionalSimplifiedWebServiceHttpPost>, Toyz4net.Core.TraditionalSimplifiedWebService.TraditionalSimplifiedWebServiceHttpPost {
        
        public TraditionalSimplifiedWebServiceHttpPostClient() {
        }
        
        public TraditionalSimplifiedWebServiceHttpPostClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public TraditionalSimplifiedWebServiceHttpPostClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public TraditionalSimplifiedWebServiceHttpPostClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public TraditionalSimplifiedWebServiceHttpPostClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Toyz4net.Core.TraditionalSimplifiedWebService.toSimplifiedChineseResponse1 Toyz4net.Core.TraditionalSimplifiedWebService.TraditionalSimplifiedWebServiceHttpPost.toSimplifiedChinese(Toyz4net.Core.TraditionalSimplifiedWebService.toSimplifiedChineseRequest1 request) {
            return base.Channel.toSimplifiedChinese(request);
        }
        
        public string toSimplifiedChinese(string sText) {
            Toyz4net.Core.TraditionalSimplifiedWebService.toSimplifiedChineseRequest1 inValue = new Toyz4net.Core.TraditionalSimplifiedWebService.toSimplifiedChineseRequest1();
            inValue.sText = sText;
            Toyz4net.Core.TraditionalSimplifiedWebService.toSimplifiedChineseResponse1 retVal = ((Toyz4net.Core.TraditionalSimplifiedWebService.TraditionalSimplifiedWebServiceHttpPost)(this)).toSimplifiedChinese(inValue);
            return retVal.@string;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Toyz4net.Core.TraditionalSimplifiedWebService.toTraditionalChineseResponse1 Toyz4net.Core.TraditionalSimplifiedWebService.TraditionalSimplifiedWebServiceHttpPost.toTraditionalChinese(Toyz4net.Core.TraditionalSimplifiedWebService.toTraditionalChineseRequest1 request) {
            return base.Channel.toTraditionalChinese(request);
        }
        
        public string toTraditionalChinese(string sText) {
            Toyz4net.Core.TraditionalSimplifiedWebService.toTraditionalChineseRequest1 inValue = new Toyz4net.Core.TraditionalSimplifiedWebService.toTraditionalChineseRequest1();
            inValue.sText = sText;
            Toyz4net.Core.TraditionalSimplifiedWebService.toTraditionalChineseResponse1 retVal = ((Toyz4net.Core.TraditionalSimplifiedWebService.TraditionalSimplifiedWebServiceHttpPost)(this)).toTraditionalChinese(inValue);
            return retVal.@string;
        }
    }
}
