//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:2.0.50727.3623
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Toyz4net.Core.ValidateCodeWebService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://WebXml.com.cn/", ConfigurationName="ValidateCodeWebService.ValidateCodeWebServiceSoap")]
    public interface ValidateCodeWebServiceSoap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://WebXml.com.cn/smallValidateImage", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        void smallValidateImage(string byString);
        
        // CODEGEN: 参数“smallValidateByteResult”需要其他方案信息，使用参数模式无法捕获这些信息。特定属性为“System.Xml.Serialization.XmlElementAttribute”。
        [System.ServiceModel.OperationContractAttribute(Action="http://WebXml.com.cn/smallValidateByte", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        Toyz4net.Core.ValidateCodeWebService.smallValidateByteResponse smallValidateByte(Toyz4net.Core.ValidateCodeWebService.smallValidateByteRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://WebXml.com.cn/enValidateImage", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        void enValidateImage(string byString);
        
        // CODEGEN: 参数“enValidateByteResult”需要其他方案信息，使用参数模式无法捕获这些信息。特定属性为“System.Xml.Serialization.XmlElementAttribute”。
        [System.ServiceModel.OperationContractAttribute(Action="http://WebXml.com.cn/enValidateByte", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        Toyz4net.Core.ValidateCodeWebService.enValidateByteResponse enValidateByte(Toyz4net.Core.ValidateCodeWebService.enValidateByteRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://WebXml.com.cn/cnValidateImage", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        void cnValidateImage(string byString);
        
        // CODEGEN: 参数“cnValidateByteResult”需要其他方案信息，使用参数模式无法捕获这些信息。特定属性为“System.Xml.Serialization.XmlElementAttribute”。
        [System.ServiceModel.OperationContractAttribute(Action="http://WebXml.com.cn/cnValidateByte", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        Toyz4net.Core.ValidateCodeWebService.cnValidateByteResponse cnValidateByte(Toyz4net.Core.ValidateCodeWebService.cnValidateByteRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="smallValidateByte", WrapperNamespace="http://WebXml.com.cn/", IsWrapped=true)]
    public partial class smallValidateByteRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://WebXml.com.cn/", Order=0)]
        public string byString;
        
        public smallValidateByteRequest() {
        }
        
        public smallValidateByteRequest(string byString) {
            this.byString = byString;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="smallValidateByteResponse", WrapperNamespace="http://WebXml.com.cn/", IsWrapped=true)]
    public partial class smallValidateByteResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://WebXml.com.cn/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary")]
        public byte[] smallValidateByteResult;
        
        public smallValidateByteResponse() {
        }
        
        public smallValidateByteResponse(byte[] smallValidateByteResult) {
            this.smallValidateByteResult = smallValidateByteResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="enValidateByte", WrapperNamespace="http://WebXml.com.cn/", IsWrapped=true)]
    public partial class enValidateByteRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://WebXml.com.cn/", Order=0)]
        public string byString;
        
        public enValidateByteRequest() {
        }
        
        public enValidateByteRequest(string byString) {
            this.byString = byString;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="enValidateByteResponse", WrapperNamespace="http://WebXml.com.cn/", IsWrapped=true)]
    public partial class enValidateByteResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://WebXml.com.cn/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary")]
        public byte[] enValidateByteResult;
        
        public enValidateByteResponse() {
        }
        
        public enValidateByteResponse(byte[] enValidateByteResult) {
            this.enValidateByteResult = enValidateByteResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="cnValidateByte", WrapperNamespace="http://WebXml.com.cn/", IsWrapped=true)]
    public partial class cnValidateByteRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://WebXml.com.cn/", Order=0)]
        public string byString;
        
        public cnValidateByteRequest() {
        }
        
        public cnValidateByteRequest(string byString) {
            this.byString = byString;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="cnValidateByteResponse", WrapperNamespace="http://WebXml.com.cn/", IsWrapped=true)]
    public partial class cnValidateByteResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://WebXml.com.cn/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary")]
        public byte[] cnValidateByteResult;
        
        public cnValidateByteResponse() {
        }
        
        public cnValidateByteResponse(byte[] cnValidateByteResult) {
            this.cnValidateByteResult = cnValidateByteResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    public interface ValidateCodeWebServiceSoapChannel : Toyz4net.Core.ValidateCodeWebService.ValidateCodeWebServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    public partial class ValidateCodeWebServiceSoapClient : System.ServiceModel.ClientBase<Toyz4net.Core.ValidateCodeWebService.ValidateCodeWebServiceSoap>, Toyz4net.Core.ValidateCodeWebService.ValidateCodeWebServiceSoap {
        
        public ValidateCodeWebServiceSoapClient() {
        }
        
        public ValidateCodeWebServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ValidateCodeWebServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ValidateCodeWebServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ValidateCodeWebServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public void smallValidateImage(string byString) {
            base.Channel.smallValidateImage(byString);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Toyz4net.Core.ValidateCodeWebService.smallValidateByteResponse Toyz4net.Core.ValidateCodeWebService.ValidateCodeWebServiceSoap.smallValidateByte(Toyz4net.Core.ValidateCodeWebService.smallValidateByteRequest request) {
            return base.Channel.smallValidateByte(request);
        }
        
        public byte[] smallValidateByte(string byString) {
            Toyz4net.Core.ValidateCodeWebService.smallValidateByteRequest inValue = new Toyz4net.Core.ValidateCodeWebService.smallValidateByteRequest();
            inValue.byString = byString;
            Toyz4net.Core.ValidateCodeWebService.smallValidateByteResponse retVal = ((Toyz4net.Core.ValidateCodeWebService.ValidateCodeWebServiceSoap)(this)).smallValidateByte(inValue);
            return retVal.smallValidateByteResult;
        }
        
        public void enValidateImage(string byString) {
            base.Channel.enValidateImage(byString);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Toyz4net.Core.ValidateCodeWebService.enValidateByteResponse Toyz4net.Core.ValidateCodeWebService.ValidateCodeWebServiceSoap.enValidateByte(Toyz4net.Core.ValidateCodeWebService.enValidateByteRequest request) {
            return base.Channel.enValidateByte(request);
        }
        
        public byte[] enValidateByte(string byString) {
            Toyz4net.Core.ValidateCodeWebService.enValidateByteRequest inValue = new Toyz4net.Core.ValidateCodeWebService.enValidateByteRequest();
            inValue.byString = byString;
            Toyz4net.Core.ValidateCodeWebService.enValidateByteResponse retVal = ((Toyz4net.Core.ValidateCodeWebService.ValidateCodeWebServiceSoap)(this)).enValidateByte(inValue);
            return retVal.enValidateByteResult;
        }
        
        public void cnValidateImage(string byString) {
            base.Channel.cnValidateImage(byString);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Toyz4net.Core.ValidateCodeWebService.cnValidateByteResponse Toyz4net.Core.ValidateCodeWebService.ValidateCodeWebServiceSoap.cnValidateByte(Toyz4net.Core.ValidateCodeWebService.cnValidateByteRequest request) {
            return base.Channel.cnValidateByte(request);
        }
        
        public byte[] cnValidateByte(string byString) {
            Toyz4net.Core.ValidateCodeWebService.cnValidateByteRequest inValue = new Toyz4net.Core.ValidateCodeWebService.cnValidateByteRequest();
            inValue.byString = byString;
            Toyz4net.Core.ValidateCodeWebService.cnValidateByteResponse retVal = ((Toyz4net.Core.ValidateCodeWebService.ValidateCodeWebServiceSoap)(this)).cnValidateByte(inValue);
            return retVal.cnValidateByteResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://WebXml.com.cn/", ConfigurationName="ValidateCodeWebService.ValidateCodeWebServiceHttpGet")]
    public interface ValidateCodeWebServiceHttpGet {
        
        // CODEGEN: 操作 smallValidateImage 以后生成的消息协定不是 RPC，也不是换行文档。
        [System.ServiceModel.OperationContractAttribute(Action="http://WebXml.com.cn/ValidateCodeWebServiceHttpGet/smallValidateImageRequest", ReplyAction="http://WebXml.com.cn/ValidateCodeWebServiceHttpGet/smallValidateImageResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        Toyz4net.Core.ValidateCodeWebService.smallValidateImageResponse smallValidateImage(Toyz4net.Core.ValidateCodeWebService.smallValidateImageRequest request);
        
        // CODEGEN: 操作 smallValidateByte 以后生成的消息协定不是 RPC，也不是换行文档。
        [System.ServiceModel.OperationContractAttribute(Action="http://WebXml.com.cn/ValidateCodeWebServiceHttpGet/smallValidateByteRequest", ReplyAction="http://WebXml.com.cn/ValidateCodeWebServiceHttpGet/smallValidateByteResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        Toyz4net.Core.ValidateCodeWebService.smallValidateByteResponse1 smallValidateByte(Toyz4net.Core.ValidateCodeWebService.smallValidateByteRequest1 request);
        
        // CODEGEN: 操作 enValidateImage 以后生成的消息协定不是 RPC，也不是换行文档。
        [System.ServiceModel.OperationContractAttribute(Action="http://WebXml.com.cn/ValidateCodeWebServiceHttpGet/enValidateImageRequest", ReplyAction="http://WebXml.com.cn/ValidateCodeWebServiceHttpGet/enValidateImageResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        Toyz4net.Core.ValidateCodeWebService.enValidateImageResponse enValidateImage(Toyz4net.Core.ValidateCodeWebService.enValidateImageRequest request);
        
        // CODEGEN: 操作 enValidateByte 以后生成的消息协定不是 RPC，也不是换行文档。
        [System.ServiceModel.OperationContractAttribute(Action="http://WebXml.com.cn/ValidateCodeWebServiceHttpGet/enValidateByteRequest", ReplyAction="http://WebXml.com.cn/ValidateCodeWebServiceHttpGet/enValidateByteResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        Toyz4net.Core.ValidateCodeWebService.enValidateByteResponse1 enValidateByte(Toyz4net.Core.ValidateCodeWebService.enValidateByteRequest1 request);
        
        // CODEGEN: 操作 cnValidateImage 以后生成的消息协定不是 RPC，也不是换行文档。
        [System.ServiceModel.OperationContractAttribute(Action="http://WebXml.com.cn/ValidateCodeWebServiceHttpGet/cnValidateImageRequest", ReplyAction="http://WebXml.com.cn/ValidateCodeWebServiceHttpGet/cnValidateImageResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        Toyz4net.Core.ValidateCodeWebService.cnValidateImageResponse cnValidateImage(Toyz4net.Core.ValidateCodeWebService.cnValidateImageRequest request);
        
        // CODEGEN: 操作 cnValidateByte 以后生成的消息协定不是 RPC，也不是换行文档。
        [System.ServiceModel.OperationContractAttribute(Action="http://WebXml.com.cn/ValidateCodeWebServiceHttpGet/cnValidateByteRequest", ReplyAction="http://WebXml.com.cn/ValidateCodeWebServiceHttpGet/cnValidateByteResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        Toyz4net.Core.ValidateCodeWebService.cnValidateByteResponse1 cnValidateByte(Toyz4net.Core.ValidateCodeWebService.cnValidateByteRequest1 request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class smallValidateImageRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string byString;
        
        public smallValidateImageRequest() {
        }
        
        public smallValidateImageRequest(string byString) {
            this.byString = byString;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class smallValidateImageResponse {
        
        public smallValidateImageResponse() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class smallValidateByteRequest1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string byString;
        
        public smallValidateByteRequest1() {
        }
        
        public smallValidateByteRequest1(string byString) {
            this.byString = byString;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class smallValidateByteResponse1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://WebXml.com.cn/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary", IsNullable=true)]
        public byte[] base64Binary;
        
        public smallValidateByteResponse1() {
        }
        
        public smallValidateByteResponse1(byte[] base64Binary) {
            this.base64Binary = base64Binary;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class enValidateImageRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string byString;
        
        public enValidateImageRequest() {
        }
        
        public enValidateImageRequest(string byString) {
            this.byString = byString;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class enValidateImageResponse {
        
        public enValidateImageResponse() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class enValidateByteRequest1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string byString;
        
        public enValidateByteRequest1() {
        }
        
        public enValidateByteRequest1(string byString) {
            this.byString = byString;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class enValidateByteResponse1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://WebXml.com.cn/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary", IsNullable=true)]
        public byte[] base64Binary;
        
        public enValidateByteResponse1() {
        }
        
        public enValidateByteResponse1(byte[] base64Binary) {
            this.base64Binary = base64Binary;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class cnValidateImageRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string byString;
        
        public cnValidateImageRequest() {
        }
        
        public cnValidateImageRequest(string byString) {
            this.byString = byString;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class cnValidateImageResponse {
        
        public cnValidateImageResponse() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class cnValidateByteRequest1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string byString;
        
        public cnValidateByteRequest1() {
        }
        
        public cnValidateByteRequest1(string byString) {
            this.byString = byString;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class cnValidateByteResponse1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://WebXml.com.cn/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary", IsNullable=true)]
        public byte[] base64Binary;
        
        public cnValidateByteResponse1() {
        }
        
        public cnValidateByteResponse1(byte[] base64Binary) {
            this.base64Binary = base64Binary;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    public interface ValidateCodeWebServiceHttpGetChannel : Toyz4net.Core.ValidateCodeWebService.ValidateCodeWebServiceHttpGet, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    public partial class ValidateCodeWebServiceHttpGetClient : System.ServiceModel.ClientBase<Toyz4net.Core.ValidateCodeWebService.ValidateCodeWebServiceHttpGet>, Toyz4net.Core.ValidateCodeWebService.ValidateCodeWebServiceHttpGet {
        
        public ValidateCodeWebServiceHttpGetClient() {
        }
        
        public ValidateCodeWebServiceHttpGetClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ValidateCodeWebServiceHttpGetClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ValidateCodeWebServiceHttpGetClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ValidateCodeWebServiceHttpGetClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Toyz4net.Core.ValidateCodeWebService.smallValidateImageResponse Toyz4net.Core.ValidateCodeWebService.ValidateCodeWebServiceHttpGet.smallValidateImage(Toyz4net.Core.ValidateCodeWebService.smallValidateImageRequest request) {
            return base.Channel.smallValidateImage(request);
        }
        
        public void smallValidateImage(string byString) {
            Toyz4net.Core.ValidateCodeWebService.smallValidateImageRequest inValue = new Toyz4net.Core.ValidateCodeWebService.smallValidateImageRequest();
            inValue.byString = byString;
            Toyz4net.Core.ValidateCodeWebService.smallValidateImageResponse retVal = ((Toyz4net.Core.ValidateCodeWebService.ValidateCodeWebServiceHttpGet)(this)).smallValidateImage(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Toyz4net.Core.ValidateCodeWebService.smallValidateByteResponse1 Toyz4net.Core.ValidateCodeWebService.ValidateCodeWebServiceHttpGet.smallValidateByte(Toyz4net.Core.ValidateCodeWebService.smallValidateByteRequest1 request) {
            return base.Channel.smallValidateByte(request);
        }
        
        public byte[] smallValidateByte(string byString) {
            Toyz4net.Core.ValidateCodeWebService.smallValidateByteRequest1 inValue = new Toyz4net.Core.ValidateCodeWebService.smallValidateByteRequest1();
            inValue.byString = byString;
            Toyz4net.Core.ValidateCodeWebService.smallValidateByteResponse1 retVal = ((Toyz4net.Core.ValidateCodeWebService.ValidateCodeWebServiceHttpGet)(this)).smallValidateByte(inValue);
            return retVal.base64Binary;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Toyz4net.Core.ValidateCodeWebService.enValidateImageResponse Toyz4net.Core.ValidateCodeWebService.ValidateCodeWebServiceHttpGet.enValidateImage(Toyz4net.Core.ValidateCodeWebService.enValidateImageRequest request) {
            return base.Channel.enValidateImage(request);
        }
        
        public void enValidateImage(string byString) {
            Toyz4net.Core.ValidateCodeWebService.enValidateImageRequest inValue = new Toyz4net.Core.ValidateCodeWebService.enValidateImageRequest();
            inValue.byString = byString;
            Toyz4net.Core.ValidateCodeWebService.enValidateImageResponse retVal = ((Toyz4net.Core.ValidateCodeWebService.ValidateCodeWebServiceHttpGet)(this)).enValidateImage(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Toyz4net.Core.ValidateCodeWebService.enValidateByteResponse1 Toyz4net.Core.ValidateCodeWebService.ValidateCodeWebServiceHttpGet.enValidateByte(Toyz4net.Core.ValidateCodeWebService.enValidateByteRequest1 request) {
            return base.Channel.enValidateByte(request);
        }
        
        public byte[] enValidateByte(string byString) {
            Toyz4net.Core.ValidateCodeWebService.enValidateByteRequest1 inValue = new Toyz4net.Core.ValidateCodeWebService.enValidateByteRequest1();
            inValue.byString = byString;
            Toyz4net.Core.ValidateCodeWebService.enValidateByteResponse1 retVal = ((Toyz4net.Core.ValidateCodeWebService.ValidateCodeWebServiceHttpGet)(this)).enValidateByte(inValue);
            return retVal.base64Binary;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Toyz4net.Core.ValidateCodeWebService.cnValidateImageResponse Toyz4net.Core.ValidateCodeWebService.ValidateCodeWebServiceHttpGet.cnValidateImage(Toyz4net.Core.ValidateCodeWebService.cnValidateImageRequest request) {
            return base.Channel.cnValidateImage(request);
        }
        
        public void cnValidateImage(string byString) {
            Toyz4net.Core.ValidateCodeWebService.cnValidateImageRequest inValue = new Toyz4net.Core.ValidateCodeWebService.cnValidateImageRequest();
            inValue.byString = byString;
            Toyz4net.Core.ValidateCodeWebService.cnValidateImageResponse retVal = ((Toyz4net.Core.ValidateCodeWebService.ValidateCodeWebServiceHttpGet)(this)).cnValidateImage(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Toyz4net.Core.ValidateCodeWebService.cnValidateByteResponse1 Toyz4net.Core.ValidateCodeWebService.ValidateCodeWebServiceHttpGet.cnValidateByte(Toyz4net.Core.ValidateCodeWebService.cnValidateByteRequest1 request) {
            return base.Channel.cnValidateByte(request);
        }
        
        public byte[] cnValidateByte(string byString) {
            Toyz4net.Core.ValidateCodeWebService.cnValidateByteRequest1 inValue = new Toyz4net.Core.ValidateCodeWebService.cnValidateByteRequest1();
            inValue.byString = byString;
            Toyz4net.Core.ValidateCodeWebService.cnValidateByteResponse1 retVal = ((Toyz4net.Core.ValidateCodeWebService.ValidateCodeWebServiceHttpGet)(this)).cnValidateByte(inValue);
            return retVal.base64Binary;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://WebXml.com.cn/", ConfigurationName="ValidateCodeWebService.ValidateCodeWebServiceHttpPost")]
    public interface ValidateCodeWebServiceHttpPost {
        
        // CODEGEN: 操作 smallValidateImage 以后生成的消息协定不是 RPC，也不是换行文档。
        [System.ServiceModel.OperationContractAttribute(Action="http://WebXml.com.cn/ValidateCodeWebServiceHttpPost/smallValidateImageRequest", ReplyAction="http://WebXml.com.cn/ValidateCodeWebServiceHttpPost/smallValidateImageResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        Toyz4net.Core.ValidateCodeWebService.smallValidateImageResponse1 smallValidateImage(Toyz4net.Core.ValidateCodeWebService.smallValidateImageRequest1 request);
        
        // CODEGEN: 操作 smallValidateByte 以后生成的消息协定不是 RPC，也不是换行文档。
        [System.ServiceModel.OperationContractAttribute(Action="http://WebXml.com.cn/ValidateCodeWebServiceHttpPost/smallValidateByteRequest", ReplyAction="http://WebXml.com.cn/ValidateCodeWebServiceHttpPost/smallValidateByteResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        Toyz4net.Core.ValidateCodeWebService.smallValidateByteResponse2 smallValidateByte(Toyz4net.Core.ValidateCodeWebService.smallValidateByteRequest2 request);
        
        // CODEGEN: 操作 enValidateImage 以后生成的消息协定不是 RPC，也不是换行文档。
        [System.ServiceModel.OperationContractAttribute(Action="http://WebXml.com.cn/ValidateCodeWebServiceHttpPost/enValidateImageRequest", ReplyAction="http://WebXml.com.cn/ValidateCodeWebServiceHttpPost/enValidateImageResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        Toyz4net.Core.ValidateCodeWebService.enValidateImageResponse1 enValidateImage(Toyz4net.Core.ValidateCodeWebService.enValidateImageRequest1 request);
        
        // CODEGEN: 操作 enValidateByte 以后生成的消息协定不是 RPC，也不是换行文档。
        [System.ServiceModel.OperationContractAttribute(Action="http://WebXml.com.cn/ValidateCodeWebServiceHttpPost/enValidateByteRequest", ReplyAction="http://WebXml.com.cn/ValidateCodeWebServiceHttpPost/enValidateByteResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        Toyz4net.Core.ValidateCodeWebService.enValidateByteResponse2 enValidateByte(Toyz4net.Core.ValidateCodeWebService.enValidateByteRequest2 request);
        
        // CODEGEN: 操作 cnValidateImage 以后生成的消息协定不是 RPC，也不是换行文档。
        [System.ServiceModel.OperationContractAttribute(Action="http://WebXml.com.cn/ValidateCodeWebServiceHttpPost/cnValidateImageRequest", ReplyAction="http://WebXml.com.cn/ValidateCodeWebServiceHttpPost/cnValidateImageResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        Toyz4net.Core.ValidateCodeWebService.cnValidateImageResponse1 cnValidateImage(Toyz4net.Core.ValidateCodeWebService.cnValidateImageRequest1 request);
        
        // CODEGEN: 操作 cnValidateByte 以后生成的消息协定不是 RPC，也不是换行文档。
        [System.ServiceModel.OperationContractAttribute(Action="http://WebXml.com.cn/ValidateCodeWebServiceHttpPost/cnValidateByteRequest", ReplyAction="http://WebXml.com.cn/ValidateCodeWebServiceHttpPost/cnValidateByteResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        Toyz4net.Core.ValidateCodeWebService.cnValidateByteResponse2 cnValidateByte(Toyz4net.Core.ValidateCodeWebService.cnValidateByteRequest2 request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class smallValidateImageRequest1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string byString;
        
        public smallValidateImageRequest1() {
        }
        
        public smallValidateImageRequest1(string byString) {
            this.byString = byString;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class smallValidateImageResponse1 {
        
        public smallValidateImageResponse1() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class smallValidateByteRequest2 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string byString;
        
        public smallValidateByteRequest2() {
        }
        
        public smallValidateByteRequest2(string byString) {
            this.byString = byString;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class smallValidateByteResponse2 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://WebXml.com.cn/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary", IsNullable=true)]
        public byte[] base64Binary;
        
        public smallValidateByteResponse2() {
        }
        
        public smallValidateByteResponse2(byte[] base64Binary) {
            this.base64Binary = base64Binary;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class enValidateImageRequest1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string byString;
        
        public enValidateImageRequest1() {
        }
        
        public enValidateImageRequest1(string byString) {
            this.byString = byString;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class enValidateImageResponse1 {
        
        public enValidateImageResponse1() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class enValidateByteRequest2 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string byString;
        
        public enValidateByteRequest2() {
        }
        
        public enValidateByteRequest2(string byString) {
            this.byString = byString;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class enValidateByteResponse2 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://WebXml.com.cn/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary", IsNullable=true)]
        public byte[] base64Binary;
        
        public enValidateByteResponse2() {
        }
        
        public enValidateByteResponse2(byte[] base64Binary) {
            this.base64Binary = base64Binary;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class cnValidateImageRequest1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string byString;
        
        public cnValidateImageRequest1() {
        }
        
        public cnValidateImageRequest1(string byString) {
            this.byString = byString;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class cnValidateImageResponse1 {
        
        public cnValidateImageResponse1() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class cnValidateByteRequest2 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string byString;
        
        public cnValidateByteRequest2() {
        }
        
        public cnValidateByteRequest2(string byString) {
            this.byString = byString;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class cnValidateByteResponse2 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://WebXml.com.cn/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary", IsNullable=true)]
        public byte[] base64Binary;
        
        public cnValidateByteResponse2() {
        }
        
        public cnValidateByteResponse2(byte[] base64Binary) {
            this.base64Binary = base64Binary;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    public interface ValidateCodeWebServiceHttpPostChannel : Toyz4net.Core.ValidateCodeWebService.ValidateCodeWebServiceHttpPost, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    public partial class ValidateCodeWebServiceHttpPostClient : System.ServiceModel.ClientBase<Toyz4net.Core.ValidateCodeWebService.ValidateCodeWebServiceHttpPost>, Toyz4net.Core.ValidateCodeWebService.ValidateCodeWebServiceHttpPost {
        
        public ValidateCodeWebServiceHttpPostClient() {
        }
        
        public ValidateCodeWebServiceHttpPostClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ValidateCodeWebServiceHttpPostClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ValidateCodeWebServiceHttpPostClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ValidateCodeWebServiceHttpPostClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Toyz4net.Core.ValidateCodeWebService.smallValidateImageResponse1 Toyz4net.Core.ValidateCodeWebService.ValidateCodeWebServiceHttpPost.smallValidateImage(Toyz4net.Core.ValidateCodeWebService.smallValidateImageRequest1 request) {
            return base.Channel.smallValidateImage(request);
        }
        
        public void smallValidateImage(string byString) {
            Toyz4net.Core.ValidateCodeWebService.smallValidateImageRequest1 inValue = new Toyz4net.Core.ValidateCodeWebService.smallValidateImageRequest1();
            inValue.byString = byString;
            Toyz4net.Core.ValidateCodeWebService.smallValidateImageResponse1 retVal = ((Toyz4net.Core.ValidateCodeWebService.ValidateCodeWebServiceHttpPost)(this)).smallValidateImage(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Toyz4net.Core.ValidateCodeWebService.smallValidateByteResponse2 Toyz4net.Core.ValidateCodeWebService.ValidateCodeWebServiceHttpPost.smallValidateByte(Toyz4net.Core.ValidateCodeWebService.smallValidateByteRequest2 request) {
            return base.Channel.smallValidateByte(request);
        }
        
        public byte[] smallValidateByte(string byString) {
            Toyz4net.Core.ValidateCodeWebService.smallValidateByteRequest2 inValue = new Toyz4net.Core.ValidateCodeWebService.smallValidateByteRequest2();
            inValue.byString = byString;
            Toyz4net.Core.ValidateCodeWebService.smallValidateByteResponse2 retVal = ((Toyz4net.Core.ValidateCodeWebService.ValidateCodeWebServiceHttpPost)(this)).smallValidateByte(inValue);
            return retVal.base64Binary;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Toyz4net.Core.ValidateCodeWebService.enValidateImageResponse1 Toyz4net.Core.ValidateCodeWebService.ValidateCodeWebServiceHttpPost.enValidateImage(Toyz4net.Core.ValidateCodeWebService.enValidateImageRequest1 request) {
            return base.Channel.enValidateImage(request);
        }
        
        public void enValidateImage(string byString) {
            Toyz4net.Core.ValidateCodeWebService.enValidateImageRequest1 inValue = new Toyz4net.Core.ValidateCodeWebService.enValidateImageRequest1();
            inValue.byString = byString;
            Toyz4net.Core.ValidateCodeWebService.enValidateImageResponse1 retVal = ((Toyz4net.Core.ValidateCodeWebService.ValidateCodeWebServiceHttpPost)(this)).enValidateImage(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Toyz4net.Core.ValidateCodeWebService.enValidateByteResponse2 Toyz4net.Core.ValidateCodeWebService.ValidateCodeWebServiceHttpPost.enValidateByte(Toyz4net.Core.ValidateCodeWebService.enValidateByteRequest2 request) {
            return base.Channel.enValidateByte(request);
        }
        
        public byte[] enValidateByte(string byString) {
            Toyz4net.Core.ValidateCodeWebService.enValidateByteRequest2 inValue = new Toyz4net.Core.ValidateCodeWebService.enValidateByteRequest2();
            inValue.byString = byString;
            Toyz4net.Core.ValidateCodeWebService.enValidateByteResponse2 retVal = ((Toyz4net.Core.ValidateCodeWebService.ValidateCodeWebServiceHttpPost)(this)).enValidateByte(inValue);
            return retVal.base64Binary;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Toyz4net.Core.ValidateCodeWebService.cnValidateImageResponse1 Toyz4net.Core.ValidateCodeWebService.ValidateCodeWebServiceHttpPost.cnValidateImage(Toyz4net.Core.ValidateCodeWebService.cnValidateImageRequest1 request) {
            return base.Channel.cnValidateImage(request);
        }
        
        public void cnValidateImage(string byString) {
            Toyz4net.Core.ValidateCodeWebService.cnValidateImageRequest1 inValue = new Toyz4net.Core.ValidateCodeWebService.cnValidateImageRequest1();
            inValue.byString = byString;
            Toyz4net.Core.ValidateCodeWebService.cnValidateImageResponse1 retVal = ((Toyz4net.Core.ValidateCodeWebService.ValidateCodeWebServiceHttpPost)(this)).cnValidateImage(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Toyz4net.Core.ValidateCodeWebService.cnValidateByteResponse2 Toyz4net.Core.ValidateCodeWebService.ValidateCodeWebServiceHttpPost.cnValidateByte(Toyz4net.Core.ValidateCodeWebService.cnValidateByteRequest2 request) {
            return base.Channel.cnValidateByte(request);
        }
        
        public byte[] cnValidateByte(string byString) {
            Toyz4net.Core.ValidateCodeWebService.cnValidateByteRequest2 inValue = new Toyz4net.Core.ValidateCodeWebService.cnValidateByteRequest2();
            inValue.byString = byString;
            Toyz4net.Core.ValidateCodeWebService.cnValidateByteResponse2 retVal = ((Toyz4net.Core.ValidateCodeWebService.ValidateCodeWebServiceHttpPost)(this)).cnValidateByte(inValue);
            return retVal.base64Binary;
        }
    }
}
