//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:2.0.50727.3623
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Toyz4net.Core.WeatherWebService {
    using System.Data;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://WebXml.com.cn/", ConfigurationName="WeatherWebService.WeatherWebServiceSoap")]
    public interface WeatherWebServiceSoap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://WebXml.com.cn/getSupportCity", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        string[] getSupportCity(string byProvinceName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://WebXml.com.cn/getSupportProvince", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        string[] getSupportProvince();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://WebXml.com.cn/getSupportDataSet", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        System.Data.DataSet getSupportDataSet();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://WebXml.com.cn/getWeatherbyCityName", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        string[] getWeatherbyCityName(string theCityName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://WebXml.com.cn/getWeatherbyCityNamePro", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        string[] getWeatherbyCityNamePro(string theCityName, string theUserID);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    public interface WeatherWebServiceSoapChannel : Toyz4net.Core.WeatherWebService.WeatherWebServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    public partial class WeatherWebServiceSoapClient : System.ServiceModel.ClientBase<Toyz4net.Core.WeatherWebService.WeatherWebServiceSoap>, Toyz4net.Core.WeatherWebService.WeatherWebServiceSoap {
        
        public WeatherWebServiceSoapClient() {
        }
        
        public WeatherWebServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WeatherWebServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WeatherWebServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WeatherWebServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string[] getSupportCity(string byProvinceName) {
            return base.Channel.getSupportCity(byProvinceName);
        }
        
        public string[] getSupportProvince() {
            return base.Channel.getSupportProvince();
        }
        
        public System.Data.DataSet getSupportDataSet() {
            return base.Channel.getSupportDataSet();
        }
        
        public string[] getWeatherbyCityName(string theCityName) {
            return base.Channel.getWeatherbyCityName(theCityName);
        }
        
        public string[] getWeatherbyCityNamePro(string theCityName, string theUserID) {
            return base.Channel.getWeatherbyCityNamePro(theCityName, theUserID);
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://WebXml.com.cn/", ConfigurationName="WeatherWebService.WeatherWebServiceHttpGet")]
    public interface WeatherWebServiceHttpGet {
        
        // CODEGEN: 操作 getSupportCity 以后生成的消息协定不是 RPC，也不是换行文档。
        [System.ServiceModel.OperationContractAttribute(Action="http://WebXml.com.cn/WeatherWebServiceHttpGet/getSupportCityRequest", ReplyAction="http://WebXml.com.cn/WeatherWebServiceHttpGet/getSupportCityResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        Toyz4net.Core.WeatherWebService.getSupportCityResponse getSupportCity(Toyz4net.Core.WeatherWebService.getSupportCityRequest request);
        
        // CODEGEN: 操作 getSupportProvince 以后生成的消息协定不是 RPC，也不是换行文档。
        [System.ServiceModel.OperationContractAttribute(Action="http://WebXml.com.cn/WeatherWebServiceHttpGet/getSupportProvinceRequest", ReplyAction="http://WebXml.com.cn/WeatherWebServiceHttpGet/getSupportProvinceResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        Toyz4net.Core.WeatherWebService.getSupportProvinceResponse getSupportProvince(Toyz4net.Core.WeatherWebService.getSupportProvinceRequest request);
        
        // CODEGEN: 操作 getSupportDataSet 以后生成的消息协定不是 RPC，也不是换行文档。
        [System.ServiceModel.OperationContractAttribute(Action="http://WebXml.com.cn/WeatherWebServiceHttpGet/getSupportDataSetRequest", ReplyAction="http://WebXml.com.cn/WeatherWebServiceHttpGet/getSupportDataSetResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        Toyz4net.Core.WeatherWebService.getSupportDataSetResponse getSupportDataSet(Toyz4net.Core.WeatherWebService.getSupportDataSetRequest request);
        
        // CODEGEN: 操作 getWeatherbyCityName 以后生成的消息协定不是 RPC，也不是换行文档。
        [System.ServiceModel.OperationContractAttribute(Action="http://WebXml.com.cn/WeatherWebServiceHttpGet/getWeatherbyCityNameRequest", ReplyAction="http://WebXml.com.cn/WeatherWebServiceHttpGet/getWeatherbyCityNameResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        Toyz4net.Core.WeatherWebService.getWeatherbyCityNameResponse getWeatherbyCityName(Toyz4net.Core.WeatherWebService.getWeatherbyCityNameRequest request);
        
        // CODEGEN: 操作 getWeatherbyCityNamePro 以后生成的消息协定不是 RPC，也不是换行文档。
        [System.ServiceModel.OperationContractAttribute(Action="http://WebXml.com.cn/WeatherWebServiceHttpGet/getWeatherbyCityNameProRequest", ReplyAction="http://WebXml.com.cn/WeatherWebServiceHttpGet/getWeatherbyCityNameProResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        Toyz4net.Core.WeatherWebService.getWeatherbyCityNameProResponse getWeatherbyCityNamePro(Toyz4net.Core.WeatherWebService.getWeatherbyCityNameProRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getSupportCityRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string byProvinceName;
        
        public getSupportCityRequest() {
        }
        
        public getSupportCityRequest(string byProvinceName) {
            this.byProvinceName = byProvinceName;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getSupportCityResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://WebXml.com.cn/", Order=0)]
        [System.Xml.Serialization.XmlArrayAttribute(IsNullable=true)]
        public string[] ArrayOfString;
        
        public getSupportCityResponse() {
        }
        
        public getSupportCityResponse(string[] ArrayOfString) {
            this.ArrayOfString = ArrayOfString;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getSupportProvinceRequest {
        
        public getSupportProvinceRequest() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getSupportProvinceResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://WebXml.com.cn/", Order=0)]
        [System.Xml.Serialization.XmlArrayAttribute(IsNullable=true)]
        public string[] ArrayOfString;
        
        public getSupportProvinceResponse() {
        }
        
        public getSupportProvinceResponse(string[] ArrayOfString) {
            this.ArrayOfString = ArrayOfString;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getSupportDataSetRequest {
        
        public getSupportDataSetRequest() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getSupportDataSetResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://WebXml.com.cn/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Data.DataSet DataSet;
        
        public getSupportDataSetResponse() {
        }
        
        public getSupportDataSetResponse(System.Data.DataSet DataSet) {
            this.DataSet = DataSet;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getWeatherbyCityNameRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string theCityName;
        
        public getWeatherbyCityNameRequest() {
        }
        
        public getWeatherbyCityNameRequest(string theCityName) {
            this.theCityName = theCityName;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getWeatherbyCityNameResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://WebXml.com.cn/", Order=0)]
        [System.Xml.Serialization.XmlArrayAttribute(IsNullable=true)]
        public string[] ArrayOfString;
        
        public getWeatherbyCityNameResponse() {
        }
        
        public getWeatherbyCityNameResponse(string[] ArrayOfString) {
            this.ArrayOfString = ArrayOfString;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getWeatherbyCityNameProRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string theCityName;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=1)]
        public string theUserID;
        
        public getWeatherbyCityNameProRequest() {
        }
        
        public getWeatherbyCityNameProRequest(string theCityName, string theUserID) {
            this.theCityName = theCityName;
            this.theUserID = theUserID;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getWeatherbyCityNameProResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://WebXml.com.cn/", Order=0)]
        [System.Xml.Serialization.XmlArrayAttribute(IsNullable=true)]
        public string[] ArrayOfString;
        
        public getWeatherbyCityNameProResponse() {
        }
        
        public getWeatherbyCityNameProResponse(string[] ArrayOfString) {
            this.ArrayOfString = ArrayOfString;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    public interface WeatherWebServiceHttpGetChannel : Toyz4net.Core.WeatherWebService.WeatherWebServiceHttpGet, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    public partial class WeatherWebServiceHttpGetClient : System.ServiceModel.ClientBase<Toyz4net.Core.WeatherWebService.WeatherWebServiceHttpGet>, Toyz4net.Core.WeatherWebService.WeatherWebServiceHttpGet {
        
        public WeatherWebServiceHttpGetClient() {
        }
        
        public WeatherWebServiceHttpGetClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WeatherWebServiceHttpGetClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WeatherWebServiceHttpGetClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WeatherWebServiceHttpGetClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Toyz4net.Core.WeatherWebService.getSupportCityResponse Toyz4net.Core.WeatherWebService.WeatherWebServiceHttpGet.getSupportCity(Toyz4net.Core.WeatherWebService.getSupportCityRequest request) {
            return base.Channel.getSupportCity(request);
        }
        
        public string[] getSupportCity(string byProvinceName) {
            Toyz4net.Core.WeatherWebService.getSupportCityRequest inValue = new Toyz4net.Core.WeatherWebService.getSupportCityRequest();
            inValue.byProvinceName = byProvinceName;
            Toyz4net.Core.WeatherWebService.getSupportCityResponse retVal = ((Toyz4net.Core.WeatherWebService.WeatherWebServiceHttpGet)(this)).getSupportCity(inValue);
            return retVal.ArrayOfString;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Toyz4net.Core.WeatherWebService.getSupportProvinceResponse Toyz4net.Core.WeatherWebService.WeatherWebServiceHttpGet.getSupportProvince(Toyz4net.Core.WeatherWebService.getSupportProvinceRequest request) {
            return base.Channel.getSupportProvince(request);
        }
        
        public string[] getSupportProvince() {
            Toyz4net.Core.WeatherWebService.getSupportProvinceRequest inValue = new Toyz4net.Core.WeatherWebService.getSupportProvinceRequest();
            Toyz4net.Core.WeatherWebService.getSupportProvinceResponse retVal = ((Toyz4net.Core.WeatherWebService.WeatherWebServiceHttpGet)(this)).getSupportProvince(inValue);
            return retVal.ArrayOfString;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Toyz4net.Core.WeatherWebService.getSupportDataSetResponse Toyz4net.Core.WeatherWebService.WeatherWebServiceHttpGet.getSupportDataSet(Toyz4net.Core.WeatherWebService.getSupportDataSetRequest request) {
            return base.Channel.getSupportDataSet(request);
        }
        
        public System.Data.DataSet getSupportDataSet() {
            Toyz4net.Core.WeatherWebService.getSupportDataSetRequest inValue = new Toyz4net.Core.WeatherWebService.getSupportDataSetRequest();
            Toyz4net.Core.WeatherWebService.getSupportDataSetResponse retVal = ((Toyz4net.Core.WeatherWebService.WeatherWebServiceHttpGet)(this)).getSupportDataSet(inValue);
            return retVal.DataSet;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Toyz4net.Core.WeatherWebService.getWeatherbyCityNameResponse Toyz4net.Core.WeatherWebService.WeatherWebServiceHttpGet.getWeatherbyCityName(Toyz4net.Core.WeatherWebService.getWeatherbyCityNameRequest request) {
            return base.Channel.getWeatherbyCityName(request);
        }
        
        public string[] getWeatherbyCityName(string theCityName) {
            Toyz4net.Core.WeatherWebService.getWeatherbyCityNameRequest inValue = new Toyz4net.Core.WeatherWebService.getWeatherbyCityNameRequest();
            inValue.theCityName = theCityName;
            Toyz4net.Core.WeatherWebService.getWeatherbyCityNameResponse retVal = ((Toyz4net.Core.WeatherWebService.WeatherWebServiceHttpGet)(this)).getWeatherbyCityName(inValue);
            return retVal.ArrayOfString;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Toyz4net.Core.WeatherWebService.getWeatherbyCityNameProResponse Toyz4net.Core.WeatherWebService.WeatherWebServiceHttpGet.getWeatherbyCityNamePro(Toyz4net.Core.WeatherWebService.getWeatherbyCityNameProRequest request) {
            return base.Channel.getWeatherbyCityNamePro(request);
        }
        
        public string[] getWeatherbyCityNamePro(string theCityName, string theUserID) {
            Toyz4net.Core.WeatherWebService.getWeatherbyCityNameProRequest inValue = new Toyz4net.Core.WeatherWebService.getWeatherbyCityNameProRequest();
            inValue.theCityName = theCityName;
            inValue.theUserID = theUserID;
            Toyz4net.Core.WeatherWebService.getWeatherbyCityNameProResponse retVal = ((Toyz4net.Core.WeatherWebService.WeatherWebServiceHttpGet)(this)).getWeatherbyCityNamePro(inValue);
            return retVal.ArrayOfString;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://WebXml.com.cn/", ConfigurationName="WeatherWebService.WeatherWebServiceHttpPost")]
    public interface WeatherWebServiceHttpPost {
        
        // CODEGEN: 操作 getSupportCity 以后生成的消息协定不是 RPC，也不是换行文档。
        [System.ServiceModel.OperationContractAttribute(Action="http://WebXml.com.cn/WeatherWebServiceHttpPost/getSupportCityRequest", ReplyAction="http://WebXml.com.cn/WeatherWebServiceHttpPost/getSupportCityResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        Toyz4net.Core.WeatherWebService.getSupportCityResponse1 getSupportCity(Toyz4net.Core.WeatherWebService.getSupportCityRequest1 request);
        
        // CODEGEN: 操作 getSupportProvince 以后生成的消息协定不是 RPC，也不是换行文档。
        [System.ServiceModel.OperationContractAttribute(Action="http://WebXml.com.cn/WeatherWebServiceHttpPost/getSupportProvinceRequest", ReplyAction="http://WebXml.com.cn/WeatherWebServiceHttpPost/getSupportProvinceResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        Toyz4net.Core.WeatherWebService.getSupportProvinceResponse1 getSupportProvince(Toyz4net.Core.WeatherWebService.getSupportProvinceRequest1 request);
        
        // CODEGEN: 操作 getSupportDataSet 以后生成的消息协定不是 RPC，也不是换行文档。
        [System.ServiceModel.OperationContractAttribute(Action="http://WebXml.com.cn/WeatherWebServiceHttpPost/getSupportDataSetRequest", ReplyAction="http://WebXml.com.cn/WeatherWebServiceHttpPost/getSupportDataSetResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        Toyz4net.Core.WeatherWebService.getSupportDataSetResponse1 getSupportDataSet(Toyz4net.Core.WeatherWebService.getSupportDataSetRequest1 request);
        
        // CODEGEN: 操作 getWeatherbyCityName 以后生成的消息协定不是 RPC，也不是换行文档。
        [System.ServiceModel.OperationContractAttribute(Action="http://WebXml.com.cn/WeatherWebServiceHttpPost/getWeatherbyCityNameRequest", ReplyAction="http://WebXml.com.cn/WeatherWebServiceHttpPost/getWeatherbyCityNameResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        Toyz4net.Core.WeatherWebService.getWeatherbyCityNameResponse1 getWeatherbyCityName(Toyz4net.Core.WeatherWebService.getWeatherbyCityNameRequest1 request);
        
        // CODEGEN: 操作 getWeatherbyCityNamePro 以后生成的消息协定不是 RPC，也不是换行文档。
        [System.ServiceModel.OperationContractAttribute(Action="http://WebXml.com.cn/WeatherWebServiceHttpPost/getWeatherbyCityNameProRequest", ReplyAction="http://WebXml.com.cn/WeatherWebServiceHttpPost/getWeatherbyCityNameProResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        Toyz4net.Core.WeatherWebService.getWeatherbyCityNameProResponse1 getWeatherbyCityNamePro(Toyz4net.Core.WeatherWebService.getWeatherbyCityNameProRequest1 request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getSupportCityRequest1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string byProvinceName;
        
        public getSupportCityRequest1() {
        }
        
        public getSupportCityRequest1(string byProvinceName) {
            this.byProvinceName = byProvinceName;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getSupportCityResponse1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://WebXml.com.cn/", Order=0)]
        [System.Xml.Serialization.XmlArrayAttribute(IsNullable=true)]
        public string[] ArrayOfString;
        
        public getSupportCityResponse1() {
        }
        
        public getSupportCityResponse1(string[] ArrayOfString) {
            this.ArrayOfString = ArrayOfString;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getSupportProvinceRequest1 {
        
        public getSupportProvinceRequest1() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getSupportProvinceResponse1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://WebXml.com.cn/", Order=0)]
        [System.Xml.Serialization.XmlArrayAttribute(IsNullable=true)]
        public string[] ArrayOfString;
        
        public getSupportProvinceResponse1() {
        }
        
        public getSupportProvinceResponse1(string[] ArrayOfString) {
            this.ArrayOfString = ArrayOfString;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getSupportDataSetRequest1 {
        
        public getSupportDataSetRequest1() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getSupportDataSetResponse1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://WebXml.com.cn/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Data.DataSet DataSet;
        
        public getSupportDataSetResponse1() {
        }
        
        public getSupportDataSetResponse1(System.Data.DataSet DataSet) {
            this.DataSet = DataSet;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getWeatherbyCityNameRequest1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string theCityName;
        
        public getWeatherbyCityNameRequest1() {
        }
        
        public getWeatherbyCityNameRequest1(string theCityName) {
            this.theCityName = theCityName;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getWeatherbyCityNameResponse1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://WebXml.com.cn/", Order=0)]
        [System.Xml.Serialization.XmlArrayAttribute(IsNullable=true)]
        public string[] ArrayOfString;
        
        public getWeatherbyCityNameResponse1() {
        }
        
        public getWeatherbyCityNameResponse1(string[] ArrayOfString) {
            this.ArrayOfString = ArrayOfString;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getWeatherbyCityNameProRequest1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string theCityName;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=1)]
        public string theUserID;
        
        public getWeatherbyCityNameProRequest1() {
        }
        
        public getWeatherbyCityNameProRequest1(string theCityName, string theUserID) {
            this.theCityName = theCityName;
            this.theUserID = theUserID;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getWeatherbyCityNameProResponse1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://WebXml.com.cn/", Order=0)]
        [System.Xml.Serialization.XmlArrayAttribute(IsNullable=true)]
        public string[] ArrayOfString;
        
        public getWeatherbyCityNameProResponse1() {
        }
        
        public getWeatherbyCityNameProResponse1(string[] ArrayOfString) {
            this.ArrayOfString = ArrayOfString;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    public interface WeatherWebServiceHttpPostChannel : Toyz4net.Core.WeatherWebService.WeatherWebServiceHttpPost, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    public partial class WeatherWebServiceHttpPostClient : System.ServiceModel.ClientBase<Toyz4net.Core.WeatherWebService.WeatherWebServiceHttpPost>, Toyz4net.Core.WeatherWebService.WeatherWebServiceHttpPost {
        
        public WeatherWebServiceHttpPostClient() {
        }
        
        public WeatherWebServiceHttpPostClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WeatherWebServiceHttpPostClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WeatherWebServiceHttpPostClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WeatherWebServiceHttpPostClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Toyz4net.Core.WeatherWebService.getSupportCityResponse1 Toyz4net.Core.WeatherWebService.WeatherWebServiceHttpPost.getSupportCity(Toyz4net.Core.WeatherWebService.getSupportCityRequest1 request) {
            return base.Channel.getSupportCity(request);
        }
        
        public string[] getSupportCity(string byProvinceName) {
            Toyz4net.Core.WeatherWebService.getSupportCityRequest1 inValue = new Toyz4net.Core.WeatherWebService.getSupportCityRequest1();
            inValue.byProvinceName = byProvinceName;
            Toyz4net.Core.WeatherWebService.getSupportCityResponse1 retVal = ((Toyz4net.Core.WeatherWebService.WeatherWebServiceHttpPost)(this)).getSupportCity(inValue);
            return retVal.ArrayOfString;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Toyz4net.Core.WeatherWebService.getSupportProvinceResponse1 Toyz4net.Core.WeatherWebService.WeatherWebServiceHttpPost.getSupportProvince(Toyz4net.Core.WeatherWebService.getSupportProvinceRequest1 request) {
            return base.Channel.getSupportProvince(request);
        }
        
        public string[] getSupportProvince() {
            Toyz4net.Core.WeatherWebService.getSupportProvinceRequest1 inValue = new Toyz4net.Core.WeatherWebService.getSupportProvinceRequest1();
            Toyz4net.Core.WeatherWebService.getSupportProvinceResponse1 retVal = ((Toyz4net.Core.WeatherWebService.WeatherWebServiceHttpPost)(this)).getSupportProvince(inValue);
            return retVal.ArrayOfString;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Toyz4net.Core.WeatherWebService.getSupportDataSetResponse1 Toyz4net.Core.WeatherWebService.WeatherWebServiceHttpPost.getSupportDataSet(Toyz4net.Core.WeatherWebService.getSupportDataSetRequest1 request) {
            return base.Channel.getSupportDataSet(request);
        }
        
        public System.Data.DataSet getSupportDataSet() {
            Toyz4net.Core.WeatherWebService.getSupportDataSetRequest1 inValue = new Toyz4net.Core.WeatherWebService.getSupportDataSetRequest1();
            Toyz4net.Core.WeatherWebService.getSupportDataSetResponse1 retVal = ((Toyz4net.Core.WeatherWebService.WeatherWebServiceHttpPost)(this)).getSupportDataSet(inValue);
            return retVal.DataSet;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Toyz4net.Core.WeatherWebService.getWeatherbyCityNameResponse1 Toyz4net.Core.WeatherWebService.WeatherWebServiceHttpPost.getWeatherbyCityName(Toyz4net.Core.WeatherWebService.getWeatherbyCityNameRequest1 request) {
            return base.Channel.getWeatherbyCityName(request);
        }
        
        public string[] getWeatherbyCityName(string theCityName) {
            Toyz4net.Core.WeatherWebService.getWeatherbyCityNameRequest1 inValue = new Toyz4net.Core.WeatherWebService.getWeatherbyCityNameRequest1();
            inValue.theCityName = theCityName;
            Toyz4net.Core.WeatherWebService.getWeatherbyCityNameResponse1 retVal = ((Toyz4net.Core.WeatherWebService.WeatherWebServiceHttpPost)(this)).getWeatherbyCityName(inValue);
            return retVal.ArrayOfString;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Toyz4net.Core.WeatherWebService.getWeatherbyCityNameProResponse1 Toyz4net.Core.WeatherWebService.WeatherWebServiceHttpPost.getWeatherbyCityNamePro(Toyz4net.Core.WeatherWebService.getWeatherbyCityNameProRequest1 request) {
            return base.Channel.getWeatherbyCityNamePro(request);
        }
        
        public string[] getWeatherbyCityNamePro(string theCityName, string theUserID) {
            Toyz4net.Core.WeatherWebService.getWeatherbyCityNameProRequest1 inValue = new Toyz4net.Core.WeatherWebService.getWeatherbyCityNameProRequest1();
            inValue.theCityName = theCityName;
            inValue.theUserID = theUserID;
            Toyz4net.Core.WeatherWebService.getWeatherbyCityNameProResponse1 retVal = ((Toyz4net.Core.WeatherWebService.WeatherWebServiceHttpPost)(this)).getWeatherbyCityNamePro(inValue);
            return retVal.ArrayOfString;
        }
    }
}
