//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:2.0.50727.3625
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Toyz4net.Core.ChinaZipSearchWebService {
    using System.Data;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://WebXml.com.cn/", ConfigurationName="ChinaZipSearchWebService.ChinaZipSearchWebServiceSoap")]
    public interface ChinaZipSearchWebServiceSoap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://WebXml.com.cn/getSupportProvince", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        string[] getSupportProvince();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://WebXml.com.cn/getSupportCity", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        string[] getSupportCity(string byProvinceName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://WebXml.com.cn/getSupportProvinceCity", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        System.Data.DataSet getSupportProvinceCity();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://WebXml.com.cn/getAddressByZipCode", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        System.Data.DataSet getAddressByZipCode(string theZipCode, string userID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://WebXml.com.cn/getZipCodeByAddress", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        System.Data.DataSet getZipCodeByAddress(string theProvinceName, string theCityName, string theAddress, string userID);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    public interface ChinaZipSearchWebServiceSoapChannel : Toyz4net.Core.ChinaZipSearchWebService.ChinaZipSearchWebServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    public partial class ChinaZipSearchWebServiceSoapClient : System.ServiceModel.ClientBase<Toyz4net.Core.ChinaZipSearchWebService.ChinaZipSearchWebServiceSoap>, Toyz4net.Core.ChinaZipSearchWebService.ChinaZipSearchWebServiceSoap {
        
        public ChinaZipSearchWebServiceSoapClient() {
        }
        
        public ChinaZipSearchWebServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ChinaZipSearchWebServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ChinaZipSearchWebServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ChinaZipSearchWebServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string[] getSupportProvince() {
            return base.Channel.getSupportProvince();
        }
        
        public string[] getSupportCity(string byProvinceName) {
            return base.Channel.getSupportCity(byProvinceName);
        }
        
        public System.Data.DataSet getSupportProvinceCity() {
            return base.Channel.getSupportProvinceCity();
        }
        
        public System.Data.DataSet getAddressByZipCode(string theZipCode, string userID) {
            return base.Channel.getAddressByZipCode(theZipCode, userID);
        }
        
        public System.Data.DataSet getZipCodeByAddress(string theProvinceName, string theCityName, string theAddress, string userID) {
            return base.Channel.getZipCodeByAddress(theProvinceName, theCityName, theAddress, userID);
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://WebXml.com.cn/", ConfigurationName="ChinaZipSearchWebService.ChinaZipSearchWebServiceHttpGet")]
    public interface ChinaZipSearchWebServiceHttpGet {
        
        // CODEGEN: 操作 getSupportProvince 以后生成的消息协定不是 RPC，也不是换行文档。
        [System.ServiceModel.OperationContractAttribute(Action="http://WebXml.com.cn/ChinaZipSearchWebServiceHttpGet/getSupportProvinceRequest", ReplyAction="http://WebXml.com.cn/ChinaZipSearchWebServiceHttpGet/getSupportProvinceResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        Toyz4net.Core.ChinaZipSearchWebService.getSupportProvinceResponse getSupportProvince(Toyz4net.Core.ChinaZipSearchWebService.getSupportProvinceRequest request);
        
        // CODEGEN: 操作 getSupportCity 以后生成的消息协定不是 RPC，也不是换行文档。
        [System.ServiceModel.OperationContractAttribute(Action="http://WebXml.com.cn/ChinaZipSearchWebServiceHttpGet/getSupportCityRequest", ReplyAction="http://WebXml.com.cn/ChinaZipSearchWebServiceHttpGet/getSupportCityResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        Toyz4net.Core.ChinaZipSearchWebService.getSupportCityResponse getSupportCity(Toyz4net.Core.ChinaZipSearchWebService.getSupportCityRequest request);
        
        // CODEGEN: 操作 getSupportProvinceCity 以后生成的消息协定不是 RPC，也不是换行文档。
        [System.ServiceModel.OperationContractAttribute(Action="http://WebXml.com.cn/ChinaZipSearchWebServiceHttpGet/getSupportProvinceCityReques" +
            "t", ReplyAction="http://WebXml.com.cn/ChinaZipSearchWebServiceHttpGet/getSupportProvinceCityRespon" +
            "se")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        Toyz4net.Core.ChinaZipSearchWebService.getSupportProvinceCityResponse getSupportProvinceCity(Toyz4net.Core.ChinaZipSearchWebService.getSupportProvinceCityRequest request);
        
        // CODEGEN: 操作 getAddressByZipCode 以后生成的消息协定不是 RPC，也不是换行文档。
        [System.ServiceModel.OperationContractAttribute(Action="http://WebXml.com.cn/ChinaZipSearchWebServiceHttpGet/getAddressByZipCodeRequest", ReplyAction="http://WebXml.com.cn/ChinaZipSearchWebServiceHttpGet/getAddressByZipCodeResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        Toyz4net.Core.ChinaZipSearchWebService.getAddressByZipCodeResponse getAddressByZipCode(Toyz4net.Core.ChinaZipSearchWebService.getAddressByZipCodeRequest request);
        
        // CODEGEN: 操作 getZipCodeByAddress 以后生成的消息协定不是 RPC，也不是换行文档。
        [System.ServiceModel.OperationContractAttribute(Action="http://WebXml.com.cn/ChinaZipSearchWebServiceHttpGet/getZipCodeByAddressRequest", ReplyAction="http://WebXml.com.cn/ChinaZipSearchWebServiceHttpGet/getZipCodeByAddressResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        Toyz4net.Core.ChinaZipSearchWebService.getZipCodeByAddressResponse getZipCodeByAddress(Toyz4net.Core.ChinaZipSearchWebService.getZipCodeByAddressRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getSupportProvinceRequest {
        
        public getSupportProvinceRequest() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getSupportProvinceResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://WebXml.com.cn/", Order=0)]
        [System.Xml.Serialization.XmlArrayAttribute(IsNullable=true)]
        public string[] ArrayOfString;
        
        public getSupportProvinceResponse() {
        }
        
        public getSupportProvinceResponse(string[] ArrayOfString) {
            this.ArrayOfString = ArrayOfString;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getSupportCityRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string byProvinceName;
        
        public getSupportCityRequest() {
        }
        
        public getSupportCityRequest(string byProvinceName) {
            this.byProvinceName = byProvinceName;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getSupportCityResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://WebXml.com.cn/", Order=0)]
        [System.Xml.Serialization.XmlArrayAttribute(IsNullable=true)]
        public string[] ArrayOfString;
        
        public getSupportCityResponse() {
        }
        
        public getSupportCityResponse(string[] ArrayOfString) {
            this.ArrayOfString = ArrayOfString;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getSupportProvinceCityRequest {
        
        public getSupportProvinceCityRequest() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getSupportProvinceCityResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://WebXml.com.cn/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Data.DataSet DataSet;
        
        public getSupportProvinceCityResponse() {
        }
        
        public getSupportProvinceCityResponse(System.Data.DataSet DataSet) {
            this.DataSet = DataSet;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getAddressByZipCodeRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string theZipCode;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=1)]
        public string userID;
        
        public getAddressByZipCodeRequest() {
        }
        
        public getAddressByZipCodeRequest(string theZipCode, string userID) {
            this.theZipCode = theZipCode;
            this.userID = userID;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getAddressByZipCodeResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://WebXml.com.cn/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Data.DataSet DataSet;
        
        public getAddressByZipCodeResponse() {
        }
        
        public getAddressByZipCodeResponse(System.Data.DataSet DataSet) {
            this.DataSet = DataSet;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getZipCodeByAddressRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string theProvinceName;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=1)]
        public string theCityName;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=2)]
        public string theAddress;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=3)]
        public string userID;
        
        public getZipCodeByAddressRequest() {
        }
        
        public getZipCodeByAddressRequest(string theProvinceName, string theCityName, string theAddress, string userID) {
            this.theProvinceName = theProvinceName;
            this.theCityName = theCityName;
            this.theAddress = theAddress;
            this.userID = userID;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getZipCodeByAddressResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://WebXml.com.cn/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Data.DataSet DataSet;
        
        public getZipCodeByAddressResponse() {
        }
        
        public getZipCodeByAddressResponse(System.Data.DataSet DataSet) {
            this.DataSet = DataSet;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    public interface ChinaZipSearchWebServiceHttpGetChannel : Toyz4net.Core.ChinaZipSearchWebService.ChinaZipSearchWebServiceHttpGet, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    public partial class ChinaZipSearchWebServiceHttpGetClient : System.ServiceModel.ClientBase<Toyz4net.Core.ChinaZipSearchWebService.ChinaZipSearchWebServiceHttpGet>, Toyz4net.Core.ChinaZipSearchWebService.ChinaZipSearchWebServiceHttpGet {
        
        public ChinaZipSearchWebServiceHttpGetClient() {
        }
        
        public ChinaZipSearchWebServiceHttpGetClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ChinaZipSearchWebServiceHttpGetClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ChinaZipSearchWebServiceHttpGetClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ChinaZipSearchWebServiceHttpGetClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Toyz4net.Core.ChinaZipSearchWebService.getSupportProvinceResponse Toyz4net.Core.ChinaZipSearchWebService.ChinaZipSearchWebServiceHttpGet.getSupportProvince(Toyz4net.Core.ChinaZipSearchWebService.getSupportProvinceRequest request) {
            return base.Channel.getSupportProvince(request);
        }
        
        public string[] getSupportProvince() {
            Toyz4net.Core.ChinaZipSearchWebService.getSupportProvinceRequest inValue = new Toyz4net.Core.ChinaZipSearchWebService.getSupportProvinceRequest();
            Toyz4net.Core.ChinaZipSearchWebService.getSupportProvinceResponse retVal = ((Toyz4net.Core.ChinaZipSearchWebService.ChinaZipSearchWebServiceHttpGet)(this)).getSupportProvince(inValue);
            return retVal.ArrayOfString;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Toyz4net.Core.ChinaZipSearchWebService.getSupportCityResponse Toyz4net.Core.ChinaZipSearchWebService.ChinaZipSearchWebServiceHttpGet.getSupportCity(Toyz4net.Core.ChinaZipSearchWebService.getSupportCityRequest request) {
            return base.Channel.getSupportCity(request);
        }
        
        public string[] getSupportCity(string byProvinceName) {
            Toyz4net.Core.ChinaZipSearchWebService.getSupportCityRequest inValue = new Toyz4net.Core.ChinaZipSearchWebService.getSupportCityRequest();
            inValue.byProvinceName = byProvinceName;
            Toyz4net.Core.ChinaZipSearchWebService.getSupportCityResponse retVal = ((Toyz4net.Core.ChinaZipSearchWebService.ChinaZipSearchWebServiceHttpGet)(this)).getSupportCity(inValue);
            return retVal.ArrayOfString;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Toyz4net.Core.ChinaZipSearchWebService.getSupportProvinceCityResponse Toyz4net.Core.ChinaZipSearchWebService.ChinaZipSearchWebServiceHttpGet.getSupportProvinceCity(Toyz4net.Core.ChinaZipSearchWebService.getSupportProvinceCityRequest request) {
            return base.Channel.getSupportProvinceCity(request);
        }
        
        public System.Data.DataSet getSupportProvinceCity() {
            Toyz4net.Core.ChinaZipSearchWebService.getSupportProvinceCityRequest inValue = new Toyz4net.Core.ChinaZipSearchWebService.getSupportProvinceCityRequest();
            Toyz4net.Core.ChinaZipSearchWebService.getSupportProvinceCityResponse retVal = ((Toyz4net.Core.ChinaZipSearchWebService.ChinaZipSearchWebServiceHttpGet)(this)).getSupportProvinceCity(inValue);
            return retVal.DataSet;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Toyz4net.Core.ChinaZipSearchWebService.getAddressByZipCodeResponse Toyz4net.Core.ChinaZipSearchWebService.ChinaZipSearchWebServiceHttpGet.getAddressByZipCode(Toyz4net.Core.ChinaZipSearchWebService.getAddressByZipCodeRequest request) {
            return base.Channel.getAddressByZipCode(request);
        }
        
        public System.Data.DataSet getAddressByZipCode(string theZipCode, string userID) {
            Toyz4net.Core.ChinaZipSearchWebService.getAddressByZipCodeRequest inValue = new Toyz4net.Core.ChinaZipSearchWebService.getAddressByZipCodeRequest();
            inValue.theZipCode = theZipCode;
            inValue.userID = userID;
            Toyz4net.Core.ChinaZipSearchWebService.getAddressByZipCodeResponse retVal = ((Toyz4net.Core.ChinaZipSearchWebService.ChinaZipSearchWebServiceHttpGet)(this)).getAddressByZipCode(inValue);
            return retVal.DataSet;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Toyz4net.Core.ChinaZipSearchWebService.getZipCodeByAddressResponse Toyz4net.Core.ChinaZipSearchWebService.ChinaZipSearchWebServiceHttpGet.getZipCodeByAddress(Toyz4net.Core.ChinaZipSearchWebService.getZipCodeByAddressRequest request) {
            return base.Channel.getZipCodeByAddress(request);
        }
        
        public System.Data.DataSet getZipCodeByAddress(string theProvinceName, string theCityName, string theAddress, string userID) {
            Toyz4net.Core.ChinaZipSearchWebService.getZipCodeByAddressRequest inValue = new Toyz4net.Core.ChinaZipSearchWebService.getZipCodeByAddressRequest();
            inValue.theProvinceName = theProvinceName;
            inValue.theCityName = theCityName;
            inValue.theAddress = theAddress;
            inValue.userID = userID;
            Toyz4net.Core.ChinaZipSearchWebService.getZipCodeByAddressResponse retVal = ((Toyz4net.Core.ChinaZipSearchWebService.ChinaZipSearchWebServiceHttpGet)(this)).getZipCodeByAddress(inValue);
            return retVal.DataSet;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://WebXml.com.cn/", ConfigurationName="ChinaZipSearchWebService.ChinaZipSearchWebServiceHttpPost")]
    public interface ChinaZipSearchWebServiceHttpPost {
        
        // CODEGEN: 操作 getSupportProvince 以后生成的消息协定不是 RPC，也不是换行文档。
        [System.ServiceModel.OperationContractAttribute(Action="http://WebXml.com.cn/ChinaZipSearchWebServiceHttpPost/getSupportProvinceRequest", ReplyAction="http://WebXml.com.cn/ChinaZipSearchWebServiceHttpPost/getSupportProvinceResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        Toyz4net.Core.ChinaZipSearchWebService.getSupportProvinceResponse1 getSupportProvince(Toyz4net.Core.ChinaZipSearchWebService.getSupportProvinceRequest1 request);
        
        // CODEGEN: 操作 getSupportCity 以后生成的消息协定不是 RPC，也不是换行文档。
        [System.ServiceModel.OperationContractAttribute(Action="http://WebXml.com.cn/ChinaZipSearchWebServiceHttpPost/getSupportCityRequest", ReplyAction="http://WebXml.com.cn/ChinaZipSearchWebServiceHttpPost/getSupportCityResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        Toyz4net.Core.ChinaZipSearchWebService.getSupportCityResponse1 getSupportCity(Toyz4net.Core.ChinaZipSearchWebService.getSupportCityRequest1 request);
        
        // CODEGEN: 操作 getSupportProvinceCity 以后生成的消息协定不是 RPC，也不是换行文档。
        [System.ServiceModel.OperationContractAttribute(Action="http://WebXml.com.cn/ChinaZipSearchWebServiceHttpPost/getSupportProvinceCityReque" +
            "st", ReplyAction="http://WebXml.com.cn/ChinaZipSearchWebServiceHttpPost/getSupportProvinceCityRespo" +
            "nse")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        Toyz4net.Core.ChinaZipSearchWebService.getSupportProvinceCityResponse1 getSupportProvinceCity(Toyz4net.Core.ChinaZipSearchWebService.getSupportProvinceCityRequest1 request);
        
        // CODEGEN: 操作 getAddressByZipCode 以后生成的消息协定不是 RPC，也不是换行文档。
        [System.ServiceModel.OperationContractAttribute(Action="http://WebXml.com.cn/ChinaZipSearchWebServiceHttpPost/getAddressByZipCodeRequest", ReplyAction="http://WebXml.com.cn/ChinaZipSearchWebServiceHttpPost/getAddressByZipCodeResponse" +
            "")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        Toyz4net.Core.ChinaZipSearchWebService.getAddressByZipCodeResponse1 getAddressByZipCode(Toyz4net.Core.ChinaZipSearchWebService.getAddressByZipCodeRequest1 request);
        
        // CODEGEN: 操作 getZipCodeByAddress 以后生成的消息协定不是 RPC，也不是换行文档。
        [System.ServiceModel.OperationContractAttribute(Action="http://WebXml.com.cn/ChinaZipSearchWebServiceHttpPost/getZipCodeByAddressRequest", ReplyAction="http://WebXml.com.cn/ChinaZipSearchWebServiceHttpPost/getZipCodeByAddressResponse" +
            "")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        Toyz4net.Core.ChinaZipSearchWebService.getZipCodeByAddressResponse1 getZipCodeByAddress(Toyz4net.Core.ChinaZipSearchWebService.getZipCodeByAddressRequest1 request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getSupportProvinceRequest1 {
        
        public getSupportProvinceRequest1() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getSupportProvinceResponse1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://WebXml.com.cn/", Order=0)]
        [System.Xml.Serialization.XmlArrayAttribute(IsNullable=true)]
        public string[] ArrayOfString;
        
        public getSupportProvinceResponse1() {
        }
        
        public getSupportProvinceResponse1(string[] ArrayOfString) {
            this.ArrayOfString = ArrayOfString;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getSupportCityRequest1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string byProvinceName;
        
        public getSupportCityRequest1() {
        }
        
        public getSupportCityRequest1(string byProvinceName) {
            this.byProvinceName = byProvinceName;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getSupportCityResponse1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://WebXml.com.cn/", Order=0)]
        [System.Xml.Serialization.XmlArrayAttribute(IsNullable=true)]
        public string[] ArrayOfString;
        
        public getSupportCityResponse1() {
        }
        
        public getSupportCityResponse1(string[] ArrayOfString) {
            this.ArrayOfString = ArrayOfString;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getSupportProvinceCityRequest1 {
        
        public getSupportProvinceCityRequest1() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getSupportProvinceCityResponse1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://WebXml.com.cn/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Data.DataSet DataSet;
        
        public getSupportProvinceCityResponse1() {
        }
        
        public getSupportProvinceCityResponse1(System.Data.DataSet DataSet) {
            this.DataSet = DataSet;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getAddressByZipCodeRequest1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string theZipCode;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=1)]
        public string userID;
        
        public getAddressByZipCodeRequest1() {
        }
        
        public getAddressByZipCodeRequest1(string theZipCode, string userID) {
            this.theZipCode = theZipCode;
            this.userID = userID;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getAddressByZipCodeResponse1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://WebXml.com.cn/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Data.DataSet DataSet;
        
        public getAddressByZipCodeResponse1() {
        }
        
        public getAddressByZipCodeResponse1(System.Data.DataSet DataSet) {
            this.DataSet = DataSet;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getZipCodeByAddressRequest1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string theProvinceName;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=1)]
        public string theCityName;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=2)]
        public string theAddress;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=3)]
        public string userID;
        
        public getZipCodeByAddressRequest1() {
        }
        
        public getZipCodeByAddressRequest1(string theProvinceName, string theCityName, string theAddress, string userID) {
            this.theProvinceName = theProvinceName;
            this.theCityName = theCityName;
            this.theAddress = theAddress;
            this.userID = userID;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getZipCodeByAddressResponse1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://WebXml.com.cn/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Data.DataSet DataSet;
        
        public getZipCodeByAddressResponse1() {
        }
        
        public getZipCodeByAddressResponse1(System.Data.DataSet DataSet) {
            this.DataSet = DataSet;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    public interface ChinaZipSearchWebServiceHttpPostChannel : Toyz4net.Core.ChinaZipSearchWebService.ChinaZipSearchWebServiceHttpPost, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    public partial class ChinaZipSearchWebServiceHttpPostClient : System.ServiceModel.ClientBase<Toyz4net.Core.ChinaZipSearchWebService.ChinaZipSearchWebServiceHttpPost>, Toyz4net.Core.ChinaZipSearchWebService.ChinaZipSearchWebServiceHttpPost {
        
        public ChinaZipSearchWebServiceHttpPostClient() {
        }
        
        public ChinaZipSearchWebServiceHttpPostClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ChinaZipSearchWebServiceHttpPostClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ChinaZipSearchWebServiceHttpPostClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ChinaZipSearchWebServiceHttpPostClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Toyz4net.Core.ChinaZipSearchWebService.getSupportProvinceResponse1 Toyz4net.Core.ChinaZipSearchWebService.ChinaZipSearchWebServiceHttpPost.getSupportProvince(Toyz4net.Core.ChinaZipSearchWebService.getSupportProvinceRequest1 request) {
            return base.Channel.getSupportProvince(request);
        }
        
        public string[] getSupportProvince() {
            Toyz4net.Core.ChinaZipSearchWebService.getSupportProvinceRequest1 inValue = new Toyz4net.Core.ChinaZipSearchWebService.getSupportProvinceRequest1();
            Toyz4net.Core.ChinaZipSearchWebService.getSupportProvinceResponse1 retVal = ((Toyz4net.Core.ChinaZipSearchWebService.ChinaZipSearchWebServiceHttpPost)(this)).getSupportProvince(inValue);
            return retVal.ArrayOfString;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Toyz4net.Core.ChinaZipSearchWebService.getSupportCityResponse1 Toyz4net.Core.ChinaZipSearchWebService.ChinaZipSearchWebServiceHttpPost.getSupportCity(Toyz4net.Core.ChinaZipSearchWebService.getSupportCityRequest1 request) {
            return base.Channel.getSupportCity(request);
        }
        
        public string[] getSupportCity(string byProvinceName) {
            Toyz4net.Core.ChinaZipSearchWebService.getSupportCityRequest1 inValue = new Toyz4net.Core.ChinaZipSearchWebService.getSupportCityRequest1();
            inValue.byProvinceName = byProvinceName;
            Toyz4net.Core.ChinaZipSearchWebService.getSupportCityResponse1 retVal = ((Toyz4net.Core.ChinaZipSearchWebService.ChinaZipSearchWebServiceHttpPost)(this)).getSupportCity(inValue);
            return retVal.ArrayOfString;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Toyz4net.Core.ChinaZipSearchWebService.getSupportProvinceCityResponse1 Toyz4net.Core.ChinaZipSearchWebService.ChinaZipSearchWebServiceHttpPost.getSupportProvinceCity(Toyz4net.Core.ChinaZipSearchWebService.getSupportProvinceCityRequest1 request) {
            return base.Channel.getSupportProvinceCity(request);
        }
        
        public System.Data.DataSet getSupportProvinceCity() {
            Toyz4net.Core.ChinaZipSearchWebService.getSupportProvinceCityRequest1 inValue = new Toyz4net.Core.ChinaZipSearchWebService.getSupportProvinceCityRequest1();
            Toyz4net.Core.ChinaZipSearchWebService.getSupportProvinceCityResponse1 retVal = ((Toyz4net.Core.ChinaZipSearchWebService.ChinaZipSearchWebServiceHttpPost)(this)).getSupportProvinceCity(inValue);
            return retVal.DataSet;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Toyz4net.Core.ChinaZipSearchWebService.getAddressByZipCodeResponse1 Toyz4net.Core.ChinaZipSearchWebService.ChinaZipSearchWebServiceHttpPost.getAddressByZipCode(Toyz4net.Core.ChinaZipSearchWebService.getAddressByZipCodeRequest1 request) {
            return base.Channel.getAddressByZipCode(request);
        }
        
        public System.Data.DataSet getAddressByZipCode(string theZipCode, string userID) {
            Toyz4net.Core.ChinaZipSearchWebService.getAddressByZipCodeRequest1 inValue = new Toyz4net.Core.ChinaZipSearchWebService.getAddressByZipCodeRequest1();
            inValue.theZipCode = theZipCode;
            inValue.userID = userID;
            Toyz4net.Core.ChinaZipSearchWebService.getAddressByZipCodeResponse1 retVal = ((Toyz4net.Core.ChinaZipSearchWebService.ChinaZipSearchWebServiceHttpPost)(this)).getAddressByZipCode(inValue);
            return retVal.DataSet;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Toyz4net.Core.ChinaZipSearchWebService.getZipCodeByAddressResponse1 Toyz4net.Core.ChinaZipSearchWebService.ChinaZipSearchWebServiceHttpPost.getZipCodeByAddress(Toyz4net.Core.ChinaZipSearchWebService.getZipCodeByAddressRequest1 request) {
            return base.Channel.getZipCodeByAddress(request);
        }
        
        public System.Data.DataSet getZipCodeByAddress(string theProvinceName, string theCityName, string theAddress, string userID) {
            Toyz4net.Core.ChinaZipSearchWebService.getZipCodeByAddressRequest1 inValue = new Toyz4net.Core.ChinaZipSearchWebService.getZipCodeByAddressRequest1();
            inValue.theProvinceName = theProvinceName;
            inValue.theCityName = theCityName;
            inValue.theAddress = theAddress;
            inValue.userID = userID;
            Toyz4net.Core.ChinaZipSearchWebService.getZipCodeByAddressResponse1 retVal = ((Toyz4net.Core.ChinaZipSearchWebService.ChinaZipSearchWebServiceHttpPost)(this)).getZipCodeByAddress(inValue);
            return retVal.DataSet;
        }
    }
}
