//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:2.0.50727.3623
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Toyz4net.Core.ValidateEmailWebService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://WebXml.com.cn/", ConfigurationName="ValidateEmailWebService.ValidateEmailWebServiceSoap")]
    public interface ValidateEmailWebServiceSoap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://WebXml.com.cn/ValidateEmailAddress", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        byte ValidateEmailAddress(string theEmail);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://WebXml.com.cn/ValidateEmailAddressPro", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        byte ValidateEmailAddressPro(string theEmail, int theEmailPort);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    public interface ValidateEmailWebServiceSoapChannel : Toyz4net.Core.ValidateEmailWebService.ValidateEmailWebServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    public partial class ValidateEmailWebServiceSoapClient : System.ServiceModel.ClientBase<Toyz4net.Core.ValidateEmailWebService.ValidateEmailWebServiceSoap>, Toyz4net.Core.ValidateEmailWebService.ValidateEmailWebServiceSoap {
        
        public ValidateEmailWebServiceSoapClient() {
        }
        
        public ValidateEmailWebServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ValidateEmailWebServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ValidateEmailWebServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ValidateEmailWebServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public byte ValidateEmailAddress(string theEmail) {
            return base.Channel.ValidateEmailAddress(theEmail);
        }
        
        public byte ValidateEmailAddressPro(string theEmail, int theEmailPort) {
            return base.Channel.ValidateEmailAddressPro(theEmail, theEmailPort);
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://WebXml.com.cn/", ConfigurationName="ValidateEmailWebService.ValidateEmailWebServiceHttpGet")]
    public interface ValidateEmailWebServiceHttpGet {
        
        // CODEGEN: 操作 ValidateEmailAddress 以后生成的消息协定不是 RPC，也不是换行文档。
        [System.ServiceModel.OperationContractAttribute(Action="http://WebXml.com.cn/ValidateEmailWebServiceHttpGet/ValidateEmailAddressRequest", ReplyAction="http://WebXml.com.cn/ValidateEmailWebServiceHttpGet/ValidateEmailAddressResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        Toyz4net.Core.ValidateEmailWebService.ValidateEmailAddressResponse ValidateEmailAddress(Toyz4net.Core.ValidateEmailWebService.ValidateEmailAddressRequest request);
        
        // CODEGEN: 操作 ValidateEmailAddressPro 以后生成的消息协定不是 RPC，也不是换行文档。
        [System.ServiceModel.OperationContractAttribute(Action="http://WebXml.com.cn/ValidateEmailWebServiceHttpGet/ValidateEmailAddressProReques" +
            "t", ReplyAction="http://WebXml.com.cn/ValidateEmailWebServiceHttpGet/ValidateEmailAddressProRespon" +
            "se")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        Toyz4net.Core.ValidateEmailWebService.ValidateEmailAddressProResponse ValidateEmailAddressPro(Toyz4net.Core.ValidateEmailWebService.ValidateEmailAddressProRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ValidateEmailAddressRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string theEmail;
        
        public ValidateEmailAddressRequest() {
        }
        
        public ValidateEmailAddressRequest(string theEmail) {
            this.theEmail = theEmail;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ValidateEmailAddressResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://WebXml.com.cn/", Order=0)]
        public byte unsignedByte;
        
        public ValidateEmailAddressResponse() {
        }
        
        public ValidateEmailAddressResponse(byte unsignedByte) {
            this.unsignedByte = unsignedByte;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ValidateEmailAddressProRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string theEmail;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=1)]
        public string theEmailPort;
        
        public ValidateEmailAddressProRequest() {
        }
        
        public ValidateEmailAddressProRequest(string theEmail, string theEmailPort) {
            this.theEmail = theEmail;
            this.theEmailPort = theEmailPort;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ValidateEmailAddressProResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://WebXml.com.cn/", Order=0)]
        public byte unsignedByte;
        
        public ValidateEmailAddressProResponse() {
        }
        
        public ValidateEmailAddressProResponse(byte unsignedByte) {
            this.unsignedByte = unsignedByte;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    public interface ValidateEmailWebServiceHttpGetChannel : Toyz4net.Core.ValidateEmailWebService.ValidateEmailWebServiceHttpGet, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    public partial class ValidateEmailWebServiceHttpGetClient : System.ServiceModel.ClientBase<Toyz4net.Core.ValidateEmailWebService.ValidateEmailWebServiceHttpGet>, Toyz4net.Core.ValidateEmailWebService.ValidateEmailWebServiceHttpGet {
        
        public ValidateEmailWebServiceHttpGetClient() {
        }
        
        public ValidateEmailWebServiceHttpGetClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ValidateEmailWebServiceHttpGetClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ValidateEmailWebServiceHttpGetClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ValidateEmailWebServiceHttpGetClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Toyz4net.Core.ValidateEmailWebService.ValidateEmailAddressResponse Toyz4net.Core.ValidateEmailWebService.ValidateEmailWebServiceHttpGet.ValidateEmailAddress(Toyz4net.Core.ValidateEmailWebService.ValidateEmailAddressRequest request) {
            return base.Channel.ValidateEmailAddress(request);
        }
        
        public byte ValidateEmailAddress(string theEmail) {
            Toyz4net.Core.ValidateEmailWebService.ValidateEmailAddressRequest inValue = new Toyz4net.Core.ValidateEmailWebService.ValidateEmailAddressRequest();
            inValue.theEmail = theEmail;
            Toyz4net.Core.ValidateEmailWebService.ValidateEmailAddressResponse retVal = ((Toyz4net.Core.ValidateEmailWebService.ValidateEmailWebServiceHttpGet)(this)).ValidateEmailAddress(inValue);
            return retVal.unsignedByte;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Toyz4net.Core.ValidateEmailWebService.ValidateEmailAddressProResponse Toyz4net.Core.ValidateEmailWebService.ValidateEmailWebServiceHttpGet.ValidateEmailAddressPro(Toyz4net.Core.ValidateEmailWebService.ValidateEmailAddressProRequest request) {
            return base.Channel.ValidateEmailAddressPro(request);
        }
        
        public byte ValidateEmailAddressPro(string theEmail, string theEmailPort) {
            Toyz4net.Core.ValidateEmailWebService.ValidateEmailAddressProRequest inValue = new Toyz4net.Core.ValidateEmailWebService.ValidateEmailAddressProRequest();
            inValue.theEmail = theEmail;
            inValue.theEmailPort = theEmailPort;
            Toyz4net.Core.ValidateEmailWebService.ValidateEmailAddressProResponse retVal = ((Toyz4net.Core.ValidateEmailWebService.ValidateEmailWebServiceHttpGet)(this)).ValidateEmailAddressPro(inValue);
            return retVal.unsignedByte;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://WebXml.com.cn/", ConfigurationName="ValidateEmailWebService.ValidateEmailWebServiceHttpPost")]
    public interface ValidateEmailWebServiceHttpPost {
        
        // CODEGEN: 操作 ValidateEmailAddress 以后生成的消息协定不是 RPC，也不是换行文档。
        [System.ServiceModel.OperationContractAttribute(Action="http://WebXml.com.cn/ValidateEmailWebServiceHttpPost/ValidateEmailAddressRequest", ReplyAction="http://WebXml.com.cn/ValidateEmailWebServiceHttpPost/ValidateEmailAddressResponse" +
            "")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        Toyz4net.Core.ValidateEmailWebService.ValidateEmailAddressResponse1 ValidateEmailAddress(Toyz4net.Core.ValidateEmailWebService.ValidateEmailAddressRequest1 request);
        
        // CODEGEN: 操作 ValidateEmailAddressPro 以后生成的消息协定不是 RPC，也不是换行文档。
        [System.ServiceModel.OperationContractAttribute(Action="http://WebXml.com.cn/ValidateEmailWebServiceHttpPost/ValidateEmailAddressProReque" +
            "st", ReplyAction="http://WebXml.com.cn/ValidateEmailWebServiceHttpPost/ValidateEmailAddressProRespo" +
            "nse")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        Toyz4net.Core.ValidateEmailWebService.ValidateEmailAddressProResponse1 ValidateEmailAddressPro(Toyz4net.Core.ValidateEmailWebService.ValidateEmailAddressProRequest1 request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ValidateEmailAddressRequest1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string theEmail;
        
        public ValidateEmailAddressRequest1() {
        }
        
        public ValidateEmailAddressRequest1(string theEmail) {
            this.theEmail = theEmail;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ValidateEmailAddressResponse1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://WebXml.com.cn/", Order=0)]
        public byte unsignedByte;
        
        public ValidateEmailAddressResponse1() {
        }
        
        public ValidateEmailAddressResponse1(byte unsignedByte) {
            this.unsignedByte = unsignedByte;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ValidateEmailAddressProRequest1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string theEmail;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=1)]
        public string theEmailPort;
        
        public ValidateEmailAddressProRequest1() {
        }
        
        public ValidateEmailAddressProRequest1(string theEmail, string theEmailPort) {
            this.theEmail = theEmail;
            this.theEmailPort = theEmailPort;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ValidateEmailAddressProResponse1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://WebXml.com.cn/", Order=0)]
        public byte unsignedByte;
        
        public ValidateEmailAddressProResponse1() {
        }
        
        public ValidateEmailAddressProResponse1(byte unsignedByte) {
            this.unsignedByte = unsignedByte;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    public interface ValidateEmailWebServiceHttpPostChannel : Toyz4net.Core.ValidateEmailWebService.ValidateEmailWebServiceHttpPost, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    public partial class ValidateEmailWebServiceHttpPostClient : System.ServiceModel.ClientBase<Toyz4net.Core.ValidateEmailWebService.ValidateEmailWebServiceHttpPost>, Toyz4net.Core.ValidateEmailWebService.ValidateEmailWebServiceHttpPost {
        
        public ValidateEmailWebServiceHttpPostClient() {
        }
        
        public ValidateEmailWebServiceHttpPostClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ValidateEmailWebServiceHttpPostClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ValidateEmailWebServiceHttpPostClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ValidateEmailWebServiceHttpPostClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Toyz4net.Core.ValidateEmailWebService.ValidateEmailAddressResponse1 Toyz4net.Core.ValidateEmailWebService.ValidateEmailWebServiceHttpPost.ValidateEmailAddress(Toyz4net.Core.ValidateEmailWebService.ValidateEmailAddressRequest1 request) {
            return base.Channel.ValidateEmailAddress(request);
        }
        
        public byte ValidateEmailAddress(string theEmail) {
            Toyz4net.Core.ValidateEmailWebService.ValidateEmailAddressRequest1 inValue = new Toyz4net.Core.ValidateEmailWebService.ValidateEmailAddressRequest1();
            inValue.theEmail = theEmail;
            Toyz4net.Core.ValidateEmailWebService.ValidateEmailAddressResponse1 retVal = ((Toyz4net.Core.ValidateEmailWebService.ValidateEmailWebServiceHttpPost)(this)).ValidateEmailAddress(inValue);
            return retVal.unsignedByte;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Toyz4net.Core.ValidateEmailWebService.ValidateEmailAddressProResponse1 Toyz4net.Core.ValidateEmailWebService.ValidateEmailWebServiceHttpPost.ValidateEmailAddressPro(Toyz4net.Core.ValidateEmailWebService.ValidateEmailAddressProRequest1 request) {
            return base.Channel.ValidateEmailAddressPro(request);
        }
        
        public byte ValidateEmailAddressPro(string theEmail, string theEmailPort) {
            Toyz4net.Core.ValidateEmailWebService.ValidateEmailAddressProRequest1 inValue = new Toyz4net.Core.ValidateEmailWebService.ValidateEmailAddressProRequest1();
            inValue.theEmail = theEmail;
            inValue.theEmailPort = theEmailPort;
            Toyz4net.Core.ValidateEmailWebService.ValidateEmailAddressProResponse1 retVal = ((Toyz4net.Core.ValidateEmailWebService.ValidateEmailWebServiceHttpPost)(this)).ValidateEmailAddressPro(inValue);
            return retVal.unsignedByte;
        }
    }
}
