//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:2.0.50727.3623
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Toyz4net.Core.WeatherWS {
    using System.Data;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://WebXml.com.cn/", ConfigurationName="WeatherWS.WeatherWSSoap")]
    public interface WeatherWSSoap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://WebXml.com.cn/getRegionDataset", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        System.Data.DataSet getRegionDataset();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://WebXml.com.cn/getRegionProvince", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        string[] getRegionProvince();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://WebXml.com.cn/getRegionCountry", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        string[] getRegionCountry();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://WebXml.com.cn/getSupportCityDataset", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        System.Data.DataSet getSupportCityDataset(string theRegionCode);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://WebXml.com.cn/getSupportCityString", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        string[] getSupportCityString(string theRegionCode);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://WebXml.com.cn/getWeather", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        string[] getWeather(string theCityCode, string theUserID);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    public interface WeatherWSSoapChannel : Toyz4net.Core.WeatherWS.WeatherWSSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    public partial class WeatherWSSoapClient : System.ServiceModel.ClientBase<Toyz4net.Core.WeatherWS.WeatherWSSoap>, Toyz4net.Core.WeatherWS.WeatherWSSoap {
        
        public WeatherWSSoapClient() {
        }
        
        public WeatherWSSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WeatherWSSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WeatherWSSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WeatherWSSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.Data.DataSet getRegionDataset() {
            return base.Channel.getRegionDataset();
        }
        
        public string[] getRegionProvince() {
            return base.Channel.getRegionProvince();
        }
        
        public string[] getRegionCountry() {
            return base.Channel.getRegionCountry();
        }
        
        public System.Data.DataSet getSupportCityDataset(string theRegionCode) {
            return base.Channel.getSupportCityDataset(theRegionCode);
        }
        
        public string[] getSupportCityString(string theRegionCode) {
            return base.Channel.getSupportCityString(theRegionCode);
        }
        
        public string[] getWeather(string theCityCode, string theUserID) {
            return base.Channel.getWeather(theCityCode, theUserID);
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://WebXml.com.cn/", ConfigurationName="WeatherWS.WeatherWSHttpGet")]
    public interface WeatherWSHttpGet {
        
        // CODEGEN: 操作 getRegionDataset 以后生成的消息协定不是 RPC，也不是换行文档。
        [System.ServiceModel.OperationContractAttribute(Action="http://WebXml.com.cn/WeatherWSHttpGet/getRegionDatasetRequest", ReplyAction="http://WebXml.com.cn/WeatherWSHttpGet/getRegionDatasetResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        Toyz4net.Core.WeatherWS.getRegionDatasetResponse getRegionDataset(Toyz4net.Core.WeatherWS.getRegionDatasetRequest request);
        
        // CODEGEN: 操作 getRegionProvince 以后生成的消息协定不是 RPC，也不是换行文档。
        [System.ServiceModel.OperationContractAttribute(Action="http://WebXml.com.cn/WeatherWSHttpGet/getRegionProvinceRequest", ReplyAction="http://WebXml.com.cn/WeatherWSHttpGet/getRegionProvinceResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        Toyz4net.Core.WeatherWS.getRegionProvinceResponse getRegionProvince(Toyz4net.Core.WeatherWS.getRegionProvinceRequest request);
        
        // CODEGEN: 操作 getRegionCountry 以后生成的消息协定不是 RPC，也不是换行文档。
        [System.ServiceModel.OperationContractAttribute(Action="http://WebXml.com.cn/WeatherWSHttpGet/getRegionCountryRequest", ReplyAction="http://WebXml.com.cn/WeatherWSHttpGet/getRegionCountryResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        Toyz4net.Core.WeatherWS.getRegionCountryResponse getRegionCountry(Toyz4net.Core.WeatherWS.getRegionCountryRequest request);
        
        // CODEGEN: 操作 getSupportCityDataset 以后生成的消息协定不是 RPC，也不是换行文档。
        [System.ServiceModel.OperationContractAttribute(Action="http://WebXml.com.cn/WeatherWSHttpGet/getSupportCityDatasetRequest", ReplyAction="http://WebXml.com.cn/WeatherWSHttpGet/getSupportCityDatasetResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        Toyz4net.Core.WeatherWS.getSupportCityDatasetResponse getSupportCityDataset(Toyz4net.Core.WeatherWS.getSupportCityDatasetRequest request);
        
        // CODEGEN: 操作 getSupportCityString 以后生成的消息协定不是 RPC，也不是换行文档。
        [System.ServiceModel.OperationContractAttribute(Action="http://WebXml.com.cn/WeatherWSHttpGet/getSupportCityStringRequest", ReplyAction="http://WebXml.com.cn/WeatherWSHttpGet/getSupportCityStringResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        Toyz4net.Core.WeatherWS.getSupportCityStringResponse getSupportCityString(Toyz4net.Core.WeatherWS.getSupportCityStringRequest request);
        
        // CODEGEN: 操作 getWeather 以后生成的消息协定不是 RPC，也不是换行文档。
        [System.ServiceModel.OperationContractAttribute(Action="http://WebXml.com.cn/WeatherWSHttpGet/getWeatherRequest", ReplyAction="http://WebXml.com.cn/WeatherWSHttpGet/getWeatherResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        Toyz4net.Core.WeatherWS.getWeatherResponse getWeather(Toyz4net.Core.WeatherWS.getWeatherRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getRegionDatasetRequest {
        
        public getRegionDatasetRequest() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getRegionDatasetResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://WebXml.com.cn/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Data.DataSet DataSet;
        
        public getRegionDatasetResponse() {
        }
        
        public getRegionDatasetResponse(System.Data.DataSet DataSet) {
            this.DataSet = DataSet;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getRegionProvinceRequest {
        
        public getRegionProvinceRequest() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getRegionProvinceResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://WebXml.com.cn/", Order=0)]
        [System.Xml.Serialization.XmlArrayAttribute(IsNullable=true)]
        public string[] ArrayOfString;
        
        public getRegionProvinceResponse() {
        }
        
        public getRegionProvinceResponse(string[] ArrayOfString) {
            this.ArrayOfString = ArrayOfString;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getRegionCountryRequest {
        
        public getRegionCountryRequest() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getRegionCountryResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://WebXml.com.cn/", Order=0)]
        [System.Xml.Serialization.XmlArrayAttribute(IsNullable=true)]
        public string[] ArrayOfString;
        
        public getRegionCountryResponse() {
        }
        
        public getRegionCountryResponse(string[] ArrayOfString) {
            this.ArrayOfString = ArrayOfString;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getSupportCityDatasetRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string theRegionCode;
        
        public getSupportCityDatasetRequest() {
        }
        
        public getSupportCityDatasetRequest(string theRegionCode) {
            this.theRegionCode = theRegionCode;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getSupportCityDatasetResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://WebXml.com.cn/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Data.DataSet DataSet;
        
        public getSupportCityDatasetResponse() {
        }
        
        public getSupportCityDatasetResponse(System.Data.DataSet DataSet) {
            this.DataSet = DataSet;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getSupportCityStringRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string theRegionCode;
        
        public getSupportCityStringRequest() {
        }
        
        public getSupportCityStringRequest(string theRegionCode) {
            this.theRegionCode = theRegionCode;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getSupportCityStringResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://WebXml.com.cn/", Order=0)]
        [System.Xml.Serialization.XmlArrayAttribute(IsNullable=true)]
        public string[] ArrayOfString;
        
        public getSupportCityStringResponse() {
        }
        
        public getSupportCityStringResponse(string[] ArrayOfString) {
            this.ArrayOfString = ArrayOfString;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getWeatherRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string theCityCode;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=1)]
        public string theUserID;
        
        public getWeatherRequest() {
        }
        
        public getWeatherRequest(string theCityCode, string theUserID) {
            this.theCityCode = theCityCode;
            this.theUserID = theUserID;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getWeatherResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://WebXml.com.cn/", Order=0)]
        [System.Xml.Serialization.XmlArrayAttribute(IsNullable=true)]
        public string[] ArrayOfString;
        
        public getWeatherResponse() {
        }
        
        public getWeatherResponse(string[] ArrayOfString) {
            this.ArrayOfString = ArrayOfString;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    public interface WeatherWSHttpGetChannel : Toyz4net.Core.WeatherWS.WeatherWSHttpGet, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    public partial class WeatherWSHttpGetClient : System.ServiceModel.ClientBase<Toyz4net.Core.WeatherWS.WeatherWSHttpGet>, Toyz4net.Core.WeatherWS.WeatherWSHttpGet {
        
        public WeatherWSHttpGetClient() {
        }
        
        public WeatherWSHttpGetClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WeatherWSHttpGetClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WeatherWSHttpGetClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WeatherWSHttpGetClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Toyz4net.Core.WeatherWS.getRegionDatasetResponse Toyz4net.Core.WeatherWS.WeatherWSHttpGet.getRegionDataset(Toyz4net.Core.WeatherWS.getRegionDatasetRequest request) {
            return base.Channel.getRegionDataset(request);
        }
        
        public System.Data.DataSet getRegionDataset() {
            Toyz4net.Core.WeatherWS.getRegionDatasetRequest inValue = new Toyz4net.Core.WeatherWS.getRegionDatasetRequest();
            Toyz4net.Core.WeatherWS.getRegionDatasetResponse retVal = ((Toyz4net.Core.WeatherWS.WeatherWSHttpGet)(this)).getRegionDataset(inValue);
            return retVal.DataSet;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Toyz4net.Core.WeatherWS.getRegionProvinceResponse Toyz4net.Core.WeatherWS.WeatherWSHttpGet.getRegionProvince(Toyz4net.Core.WeatherWS.getRegionProvinceRequest request) {
            return base.Channel.getRegionProvince(request);
        }
        
        public string[] getRegionProvince() {
            Toyz4net.Core.WeatherWS.getRegionProvinceRequest inValue = new Toyz4net.Core.WeatherWS.getRegionProvinceRequest();
            Toyz4net.Core.WeatherWS.getRegionProvinceResponse retVal = ((Toyz4net.Core.WeatherWS.WeatherWSHttpGet)(this)).getRegionProvince(inValue);
            return retVal.ArrayOfString;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Toyz4net.Core.WeatherWS.getRegionCountryResponse Toyz4net.Core.WeatherWS.WeatherWSHttpGet.getRegionCountry(Toyz4net.Core.WeatherWS.getRegionCountryRequest request) {
            return base.Channel.getRegionCountry(request);
        }
        
        public string[] getRegionCountry() {
            Toyz4net.Core.WeatherWS.getRegionCountryRequest inValue = new Toyz4net.Core.WeatherWS.getRegionCountryRequest();
            Toyz4net.Core.WeatherWS.getRegionCountryResponse retVal = ((Toyz4net.Core.WeatherWS.WeatherWSHttpGet)(this)).getRegionCountry(inValue);
            return retVal.ArrayOfString;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Toyz4net.Core.WeatherWS.getSupportCityDatasetResponse Toyz4net.Core.WeatherWS.WeatherWSHttpGet.getSupportCityDataset(Toyz4net.Core.WeatherWS.getSupportCityDatasetRequest request) {
            return base.Channel.getSupportCityDataset(request);
        }
        
        public System.Data.DataSet getSupportCityDataset(string theRegionCode) {
            Toyz4net.Core.WeatherWS.getSupportCityDatasetRequest inValue = new Toyz4net.Core.WeatherWS.getSupportCityDatasetRequest();
            inValue.theRegionCode = theRegionCode;
            Toyz4net.Core.WeatherWS.getSupportCityDatasetResponse retVal = ((Toyz4net.Core.WeatherWS.WeatherWSHttpGet)(this)).getSupportCityDataset(inValue);
            return retVal.DataSet;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Toyz4net.Core.WeatherWS.getSupportCityStringResponse Toyz4net.Core.WeatherWS.WeatherWSHttpGet.getSupportCityString(Toyz4net.Core.WeatherWS.getSupportCityStringRequest request) {
            return base.Channel.getSupportCityString(request);
        }
        
        public string[] getSupportCityString(string theRegionCode) {
            Toyz4net.Core.WeatherWS.getSupportCityStringRequest inValue = new Toyz4net.Core.WeatherWS.getSupportCityStringRequest();
            inValue.theRegionCode = theRegionCode;
            Toyz4net.Core.WeatherWS.getSupportCityStringResponse retVal = ((Toyz4net.Core.WeatherWS.WeatherWSHttpGet)(this)).getSupportCityString(inValue);
            return retVal.ArrayOfString;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Toyz4net.Core.WeatherWS.getWeatherResponse Toyz4net.Core.WeatherWS.WeatherWSHttpGet.getWeather(Toyz4net.Core.WeatherWS.getWeatherRequest request) {
            return base.Channel.getWeather(request);
        }
        
        public string[] getWeather(string theCityCode, string theUserID) {
            Toyz4net.Core.WeatherWS.getWeatherRequest inValue = new Toyz4net.Core.WeatherWS.getWeatherRequest();
            inValue.theCityCode = theCityCode;
            inValue.theUserID = theUserID;
            Toyz4net.Core.WeatherWS.getWeatherResponse retVal = ((Toyz4net.Core.WeatherWS.WeatherWSHttpGet)(this)).getWeather(inValue);
            return retVal.ArrayOfString;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://WebXml.com.cn/", ConfigurationName="WeatherWS.WeatherWSHttpPost")]
    public interface WeatherWSHttpPost {
        
        // CODEGEN: 操作 getRegionDataset 以后生成的消息协定不是 RPC，也不是换行文档。
        [System.ServiceModel.OperationContractAttribute(Action="http://WebXml.com.cn/WeatherWSHttpPost/getRegionDatasetRequest", ReplyAction="http://WebXml.com.cn/WeatherWSHttpPost/getRegionDatasetResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        Toyz4net.Core.WeatherWS.getRegionDatasetResponse1 getRegionDataset(Toyz4net.Core.WeatherWS.getRegionDatasetRequest1 request);
        
        // CODEGEN: 操作 getRegionProvince 以后生成的消息协定不是 RPC，也不是换行文档。
        [System.ServiceModel.OperationContractAttribute(Action="http://WebXml.com.cn/WeatherWSHttpPost/getRegionProvinceRequest", ReplyAction="http://WebXml.com.cn/WeatherWSHttpPost/getRegionProvinceResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        Toyz4net.Core.WeatherWS.getRegionProvinceResponse1 getRegionProvince(Toyz4net.Core.WeatherWS.getRegionProvinceRequest1 request);
        
        // CODEGEN: 操作 getRegionCountry 以后生成的消息协定不是 RPC，也不是换行文档。
        [System.ServiceModel.OperationContractAttribute(Action="http://WebXml.com.cn/WeatherWSHttpPost/getRegionCountryRequest", ReplyAction="http://WebXml.com.cn/WeatherWSHttpPost/getRegionCountryResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        Toyz4net.Core.WeatherWS.getRegionCountryResponse1 getRegionCountry(Toyz4net.Core.WeatherWS.getRegionCountryRequest1 request);
        
        // CODEGEN: 操作 getSupportCityDataset 以后生成的消息协定不是 RPC，也不是换行文档。
        [System.ServiceModel.OperationContractAttribute(Action="http://WebXml.com.cn/WeatherWSHttpPost/getSupportCityDatasetRequest", ReplyAction="http://WebXml.com.cn/WeatherWSHttpPost/getSupportCityDatasetResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        Toyz4net.Core.WeatherWS.getSupportCityDatasetResponse1 getSupportCityDataset(Toyz4net.Core.WeatherWS.getSupportCityDatasetRequest1 request);
        
        // CODEGEN: 操作 getSupportCityString 以后生成的消息协定不是 RPC，也不是换行文档。
        [System.ServiceModel.OperationContractAttribute(Action="http://WebXml.com.cn/WeatherWSHttpPost/getSupportCityStringRequest", ReplyAction="http://WebXml.com.cn/WeatherWSHttpPost/getSupportCityStringResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        Toyz4net.Core.WeatherWS.getSupportCityStringResponse1 getSupportCityString(Toyz4net.Core.WeatherWS.getSupportCityStringRequest1 request);
        
        // CODEGEN: 操作 getWeather 以后生成的消息协定不是 RPC，也不是换行文档。
        [System.ServiceModel.OperationContractAttribute(Action="http://WebXml.com.cn/WeatherWSHttpPost/getWeatherRequest", ReplyAction="http://WebXml.com.cn/WeatherWSHttpPost/getWeatherResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        Toyz4net.Core.WeatherWS.getWeatherResponse1 getWeather(Toyz4net.Core.WeatherWS.getWeatherRequest1 request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getRegionDatasetRequest1 {
        
        public getRegionDatasetRequest1() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getRegionDatasetResponse1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://WebXml.com.cn/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Data.DataSet DataSet;
        
        public getRegionDatasetResponse1() {
        }
        
        public getRegionDatasetResponse1(System.Data.DataSet DataSet) {
            this.DataSet = DataSet;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getRegionProvinceRequest1 {
        
        public getRegionProvinceRequest1() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getRegionProvinceResponse1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://WebXml.com.cn/", Order=0)]
        [System.Xml.Serialization.XmlArrayAttribute(IsNullable=true)]
        public string[] ArrayOfString;
        
        public getRegionProvinceResponse1() {
        }
        
        public getRegionProvinceResponse1(string[] ArrayOfString) {
            this.ArrayOfString = ArrayOfString;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getRegionCountryRequest1 {
        
        public getRegionCountryRequest1() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getRegionCountryResponse1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://WebXml.com.cn/", Order=0)]
        [System.Xml.Serialization.XmlArrayAttribute(IsNullable=true)]
        public string[] ArrayOfString;
        
        public getRegionCountryResponse1() {
        }
        
        public getRegionCountryResponse1(string[] ArrayOfString) {
            this.ArrayOfString = ArrayOfString;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getSupportCityDatasetRequest1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string theRegionCode;
        
        public getSupportCityDatasetRequest1() {
        }
        
        public getSupportCityDatasetRequest1(string theRegionCode) {
            this.theRegionCode = theRegionCode;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getSupportCityDatasetResponse1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://WebXml.com.cn/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Data.DataSet DataSet;
        
        public getSupportCityDatasetResponse1() {
        }
        
        public getSupportCityDatasetResponse1(System.Data.DataSet DataSet) {
            this.DataSet = DataSet;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getSupportCityStringRequest1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string theRegionCode;
        
        public getSupportCityStringRequest1() {
        }
        
        public getSupportCityStringRequest1(string theRegionCode) {
            this.theRegionCode = theRegionCode;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getSupportCityStringResponse1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://WebXml.com.cn/", Order=0)]
        [System.Xml.Serialization.XmlArrayAttribute(IsNullable=true)]
        public string[] ArrayOfString;
        
        public getSupportCityStringResponse1() {
        }
        
        public getSupportCityStringResponse1(string[] ArrayOfString) {
            this.ArrayOfString = ArrayOfString;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getWeatherRequest1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string theCityCode;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=1)]
        public string theUserID;
        
        public getWeatherRequest1() {
        }
        
        public getWeatherRequest1(string theCityCode, string theUserID) {
            this.theCityCode = theCityCode;
            this.theUserID = theUserID;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getWeatherResponse1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://WebXml.com.cn/", Order=0)]
        [System.Xml.Serialization.XmlArrayAttribute(IsNullable=true)]
        public string[] ArrayOfString;
        
        public getWeatherResponse1() {
        }
        
        public getWeatherResponse1(string[] ArrayOfString) {
            this.ArrayOfString = ArrayOfString;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    public interface WeatherWSHttpPostChannel : Toyz4net.Core.WeatherWS.WeatherWSHttpPost, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    public partial class WeatherWSHttpPostClient : System.ServiceModel.ClientBase<Toyz4net.Core.WeatherWS.WeatherWSHttpPost>, Toyz4net.Core.WeatherWS.WeatherWSHttpPost {
        
        public WeatherWSHttpPostClient() {
        }
        
        public WeatherWSHttpPostClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WeatherWSHttpPostClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WeatherWSHttpPostClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WeatherWSHttpPostClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Toyz4net.Core.WeatherWS.getRegionDatasetResponse1 Toyz4net.Core.WeatherWS.WeatherWSHttpPost.getRegionDataset(Toyz4net.Core.WeatherWS.getRegionDatasetRequest1 request) {
            return base.Channel.getRegionDataset(request);
        }
        
        public System.Data.DataSet getRegionDataset() {
            Toyz4net.Core.WeatherWS.getRegionDatasetRequest1 inValue = new Toyz4net.Core.WeatherWS.getRegionDatasetRequest1();
            Toyz4net.Core.WeatherWS.getRegionDatasetResponse1 retVal = ((Toyz4net.Core.WeatherWS.WeatherWSHttpPost)(this)).getRegionDataset(inValue);
            return retVal.DataSet;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Toyz4net.Core.WeatherWS.getRegionProvinceResponse1 Toyz4net.Core.WeatherWS.WeatherWSHttpPost.getRegionProvince(Toyz4net.Core.WeatherWS.getRegionProvinceRequest1 request) {
            return base.Channel.getRegionProvince(request);
        }
        
        public string[] getRegionProvince() {
            Toyz4net.Core.WeatherWS.getRegionProvinceRequest1 inValue = new Toyz4net.Core.WeatherWS.getRegionProvinceRequest1();
            Toyz4net.Core.WeatherWS.getRegionProvinceResponse1 retVal = ((Toyz4net.Core.WeatherWS.WeatherWSHttpPost)(this)).getRegionProvince(inValue);
            return retVal.ArrayOfString;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Toyz4net.Core.WeatherWS.getRegionCountryResponse1 Toyz4net.Core.WeatherWS.WeatherWSHttpPost.getRegionCountry(Toyz4net.Core.WeatherWS.getRegionCountryRequest1 request) {
            return base.Channel.getRegionCountry(request);
        }
        
        public string[] getRegionCountry() {
            Toyz4net.Core.WeatherWS.getRegionCountryRequest1 inValue = new Toyz4net.Core.WeatherWS.getRegionCountryRequest1();
            Toyz4net.Core.WeatherWS.getRegionCountryResponse1 retVal = ((Toyz4net.Core.WeatherWS.WeatherWSHttpPost)(this)).getRegionCountry(inValue);
            return retVal.ArrayOfString;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Toyz4net.Core.WeatherWS.getSupportCityDatasetResponse1 Toyz4net.Core.WeatherWS.WeatherWSHttpPost.getSupportCityDataset(Toyz4net.Core.WeatherWS.getSupportCityDatasetRequest1 request) {
            return base.Channel.getSupportCityDataset(request);
        }
        
        public System.Data.DataSet getSupportCityDataset(string theRegionCode) {
            Toyz4net.Core.WeatherWS.getSupportCityDatasetRequest1 inValue = new Toyz4net.Core.WeatherWS.getSupportCityDatasetRequest1();
            inValue.theRegionCode = theRegionCode;
            Toyz4net.Core.WeatherWS.getSupportCityDatasetResponse1 retVal = ((Toyz4net.Core.WeatherWS.WeatherWSHttpPost)(this)).getSupportCityDataset(inValue);
            return retVal.DataSet;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Toyz4net.Core.WeatherWS.getSupportCityStringResponse1 Toyz4net.Core.WeatherWS.WeatherWSHttpPost.getSupportCityString(Toyz4net.Core.WeatherWS.getSupportCityStringRequest1 request) {
            return base.Channel.getSupportCityString(request);
        }
        
        public string[] getSupportCityString(string theRegionCode) {
            Toyz4net.Core.WeatherWS.getSupportCityStringRequest1 inValue = new Toyz4net.Core.WeatherWS.getSupportCityStringRequest1();
            inValue.theRegionCode = theRegionCode;
            Toyz4net.Core.WeatherWS.getSupportCityStringResponse1 retVal = ((Toyz4net.Core.WeatherWS.WeatherWSHttpPost)(this)).getSupportCityString(inValue);
            return retVal.ArrayOfString;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Toyz4net.Core.WeatherWS.getWeatherResponse1 Toyz4net.Core.WeatherWS.WeatherWSHttpPost.getWeather(Toyz4net.Core.WeatherWS.getWeatherRequest1 request) {
            return base.Channel.getWeather(request);
        }
        
        public string[] getWeather(string theCityCode, string theUserID) {
            Toyz4net.Core.WeatherWS.getWeatherRequest1 inValue = new Toyz4net.Core.WeatherWS.getWeatherRequest1();
            inValue.theCityCode = theCityCode;
            inValue.theUserID = theUserID;
            Toyz4net.Core.WeatherWS.getWeatherResponse1 retVal = ((Toyz4net.Core.WeatherWS.WeatherWSHttpPost)(this)).getWeather(inValue);
            return retVal.ArrayOfString;
        }
    }
}
