//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:2.0.50727.3623
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Toyz4net.Core.MobileCodeWS {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://WebXml.com.cn/", ConfigurationName="MobileCodeWS.MobileCodeWSSoap")]
    public interface MobileCodeWSSoap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://WebXml.com.cn/getMobileCodeInfo", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        string getMobileCodeInfo(string mobileCode, string userID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://WebXml.com.cn/getDatabaseInfo", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        string[] getDatabaseInfo();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    public interface MobileCodeWSSoapChannel : Toyz4net.Core.MobileCodeWS.MobileCodeWSSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    public partial class MobileCodeWSSoapClient : System.ServiceModel.ClientBase<Toyz4net.Core.MobileCodeWS.MobileCodeWSSoap>, Toyz4net.Core.MobileCodeWS.MobileCodeWSSoap {
        
        public MobileCodeWSSoapClient() {
        }
        
        public MobileCodeWSSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public MobileCodeWSSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public MobileCodeWSSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public MobileCodeWSSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string getMobileCodeInfo(string mobileCode, string userID) {
            return base.Channel.getMobileCodeInfo(mobileCode, userID);
        }
        
        public string[] getDatabaseInfo() {
            return base.Channel.getDatabaseInfo();
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://WebXml.com.cn/", ConfigurationName="MobileCodeWS.MobileCodeWSHttpGet")]
    public interface MobileCodeWSHttpGet {
        
        // CODEGEN: 操作 getMobileCodeInfo 以后生成的消息协定不是 RPC，也不是换行文档。
        [System.ServiceModel.OperationContractAttribute(Action="http://WebXml.com.cn/MobileCodeWSHttpGet/getMobileCodeInfoRequest", ReplyAction="http://WebXml.com.cn/MobileCodeWSHttpGet/getMobileCodeInfoResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        Toyz4net.Core.MobileCodeWS.getMobileCodeInfoResponse getMobileCodeInfo(Toyz4net.Core.MobileCodeWS.getMobileCodeInfoRequest request);
        
        // CODEGEN: 操作 getDatabaseInfo 以后生成的消息协定不是 RPC，也不是换行文档。
        [System.ServiceModel.OperationContractAttribute(Action="http://WebXml.com.cn/MobileCodeWSHttpGet/getDatabaseInfoRequest", ReplyAction="http://WebXml.com.cn/MobileCodeWSHttpGet/getDatabaseInfoResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        Toyz4net.Core.MobileCodeWS.getDatabaseInfoResponse getDatabaseInfo(Toyz4net.Core.MobileCodeWS.getDatabaseInfoRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getMobileCodeInfoRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string mobileCode;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=1)]
        public string userID;
        
        public getMobileCodeInfoRequest() {
        }
        
        public getMobileCodeInfoRequest(string mobileCode, string userID) {
            this.mobileCode = mobileCode;
            this.userID = userID;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getMobileCodeInfoResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://WebXml.com.cn/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string @string;
        
        public getMobileCodeInfoResponse() {
        }
        
        public getMobileCodeInfoResponse(string @string) {
            this.@string = @string;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getDatabaseInfoRequest {
        
        public getDatabaseInfoRequest() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getDatabaseInfoResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://WebXml.com.cn/", Order=0)]
        [System.Xml.Serialization.XmlArrayAttribute(IsNullable=true)]
        public string[] ArrayOfString;
        
        public getDatabaseInfoResponse() {
        }
        
        public getDatabaseInfoResponse(string[] ArrayOfString) {
            this.ArrayOfString = ArrayOfString;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    public interface MobileCodeWSHttpGetChannel : Toyz4net.Core.MobileCodeWS.MobileCodeWSHttpGet, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    public partial class MobileCodeWSHttpGetClient : System.ServiceModel.ClientBase<Toyz4net.Core.MobileCodeWS.MobileCodeWSHttpGet>, Toyz4net.Core.MobileCodeWS.MobileCodeWSHttpGet {
        
        public MobileCodeWSHttpGetClient() {
        }
        
        public MobileCodeWSHttpGetClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public MobileCodeWSHttpGetClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public MobileCodeWSHttpGetClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public MobileCodeWSHttpGetClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Toyz4net.Core.MobileCodeWS.getMobileCodeInfoResponse Toyz4net.Core.MobileCodeWS.MobileCodeWSHttpGet.getMobileCodeInfo(Toyz4net.Core.MobileCodeWS.getMobileCodeInfoRequest request) {
            return base.Channel.getMobileCodeInfo(request);
        }
        
        public string getMobileCodeInfo(string mobileCode, string userID) {
            Toyz4net.Core.MobileCodeWS.getMobileCodeInfoRequest inValue = new Toyz4net.Core.MobileCodeWS.getMobileCodeInfoRequest();
            inValue.mobileCode = mobileCode;
            inValue.userID = userID;
            Toyz4net.Core.MobileCodeWS.getMobileCodeInfoResponse retVal = ((Toyz4net.Core.MobileCodeWS.MobileCodeWSHttpGet)(this)).getMobileCodeInfo(inValue);
            return retVal.@string;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Toyz4net.Core.MobileCodeWS.getDatabaseInfoResponse Toyz4net.Core.MobileCodeWS.MobileCodeWSHttpGet.getDatabaseInfo(Toyz4net.Core.MobileCodeWS.getDatabaseInfoRequest request) {
            return base.Channel.getDatabaseInfo(request);
        }
        
        public string[] getDatabaseInfo() {
            Toyz4net.Core.MobileCodeWS.getDatabaseInfoRequest inValue = new Toyz4net.Core.MobileCodeWS.getDatabaseInfoRequest();
            Toyz4net.Core.MobileCodeWS.getDatabaseInfoResponse retVal = ((Toyz4net.Core.MobileCodeWS.MobileCodeWSHttpGet)(this)).getDatabaseInfo(inValue);
            return retVal.ArrayOfString;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://WebXml.com.cn/", ConfigurationName="MobileCodeWS.MobileCodeWSHttpPost")]
    public interface MobileCodeWSHttpPost {
        
        // CODEGEN: 操作 getMobileCodeInfo 以后生成的消息协定不是 RPC，也不是换行文档。
        [System.ServiceModel.OperationContractAttribute(Action="http://WebXml.com.cn/MobileCodeWSHttpPost/getMobileCodeInfoRequest", ReplyAction="http://WebXml.com.cn/MobileCodeWSHttpPost/getMobileCodeInfoResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        Toyz4net.Core.MobileCodeWS.getMobileCodeInfoResponse1 getMobileCodeInfo(Toyz4net.Core.MobileCodeWS.getMobileCodeInfoRequest1 request);
        
        // CODEGEN: 操作 getDatabaseInfo 以后生成的消息协定不是 RPC，也不是换行文档。
        [System.ServiceModel.OperationContractAttribute(Action="http://WebXml.com.cn/MobileCodeWSHttpPost/getDatabaseInfoRequest", ReplyAction="http://WebXml.com.cn/MobileCodeWSHttpPost/getDatabaseInfoResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        Toyz4net.Core.MobileCodeWS.getDatabaseInfoResponse1 getDatabaseInfo(Toyz4net.Core.MobileCodeWS.getDatabaseInfoRequest1 request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getMobileCodeInfoRequest1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string mobileCode;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=1)]
        public string userID;
        
        public getMobileCodeInfoRequest1() {
        }
        
        public getMobileCodeInfoRequest1(string mobileCode, string userID) {
            this.mobileCode = mobileCode;
            this.userID = userID;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getMobileCodeInfoResponse1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://WebXml.com.cn/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string @string;
        
        public getMobileCodeInfoResponse1() {
        }
        
        public getMobileCodeInfoResponse1(string @string) {
            this.@string = @string;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getDatabaseInfoRequest1 {
        
        public getDatabaseInfoRequest1() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getDatabaseInfoResponse1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://WebXml.com.cn/", Order=0)]
        [System.Xml.Serialization.XmlArrayAttribute(IsNullable=true)]
        public string[] ArrayOfString;
        
        public getDatabaseInfoResponse1() {
        }
        
        public getDatabaseInfoResponse1(string[] ArrayOfString) {
            this.ArrayOfString = ArrayOfString;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    public interface MobileCodeWSHttpPostChannel : Toyz4net.Core.MobileCodeWS.MobileCodeWSHttpPost, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    public partial class MobileCodeWSHttpPostClient : System.ServiceModel.ClientBase<Toyz4net.Core.MobileCodeWS.MobileCodeWSHttpPost>, Toyz4net.Core.MobileCodeWS.MobileCodeWSHttpPost {
        
        public MobileCodeWSHttpPostClient() {
        }
        
        public MobileCodeWSHttpPostClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public MobileCodeWSHttpPostClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public MobileCodeWSHttpPostClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public MobileCodeWSHttpPostClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Toyz4net.Core.MobileCodeWS.getMobileCodeInfoResponse1 Toyz4net.Core.MobileCodeWS.MobileCodeWSHttpPost.getMobileCodeInfo(Toyz4net.Core.MobileCodeWS.getMobileCodeInfoRequest1 request) {
            return base.Channel.getMobileCodeInfo(request);
        }
        
        public string getMobileCodeInfo(string mobileCode, string userID) {
            Toyz4net.Core.MobileCodeWS.getMobileCodeInfoRequest1 inValue = new Toyz4net.Core.MobileCodeWS.getMobileCodeInfoRequest1();
            inValue.mobileCode = mobileCode;
            inValue.userID = userID;
            Toyz4net.Core.MobileCodeWS.getMobileCodeInfoResponse1 retVal = ((Toyz4net.Core.MobileCodeWS.MobileCodeWSHttpPost)(this)).getMobileCodeInfo(inValue);
            return retVal.@string;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Toyz4net.Core.MobileCodeWS.getDatabaseInfoResponse1 Toyz4net.Core.MobileCodeWS.MobileCodeWSHttpPost.getDatabaseInfo(Toyz4net.Core.MobileCodeWS.getDatabaseInfoRequest1 request) {
            return base.Channel.getDatabaseInfo(request);
        }
        
        public string[] getDatabaseInfo() {
            Toyz4net.Core.MobileCodeWS.getDatabaseInfoRequest1 inValue = new Toyz4net.Core.MobileCodeWS.getDatabaseInfoRequest1();
            Toyz4net.Core.MobileCodeWS.getDatabaseInfoResponse1 retVal = ((Toyz4net.Core.MobileCodeWS.MobileCodeWSHttpPost)(this)).getDatabaseInfo(inValue);
            return retVal.ArrayOfString;
        }
    }
}
