//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:2.0.50727.3623
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Toyz4net.Core.ForexRmbRateWebService {
    using System.Data;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://webxml.com.cn/", ConfigurationName="ForexRmbRateWebService.ForexRmbRateWebServiceSoap")]
    public interface ForexRmbRateWebServiceSoap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://webxml.com.cn/getForexRmbRate", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        System.Data.DataSet getForexRmbRate();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://webxml.com.cn/getForexRmbRatePro", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        System.Data.DataSet getForexRmbRatePro(string theUserID);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    public interface ForexRmbRateWebServiceSoapChannel : Toyz4net.Core.ForexRmbRateWebService.ForexRmbRateWebServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    public partial class ForexRmbRateWebServiceSoapClient : System.ServiceModel.ClientBase<Toyz4net.Core.ForexRmbRateWebService.ForexRmbRateWebServiceSoap>, Toyz4net.Core.ForexRmbRateWebService.ForexRmbRateWebServiceSoap {
        
        public ForexRmbRateWebServiceSoapClient() {
        }
        
        public ForexRmbRateWebServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ForexRmbRateWebServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ForexRmbRateWebServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ForexRmbRateWebServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.Data.DataSet getForexRmbRate() {
            return base.Channel.getForexRmbRate();
        }
        
        public System.Data.DataSet getForexRmbRatePro(string theUserID) {
            return base.Channel.getForexRmbRatePro(theUserID);
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://webxml.com.cn/", ConfigurationName="ForexRmbRateWebService.ForexRmbRateWebServiceHttpGet")]
    public interface ForexRmbRateWebServiceHttpGet {
        
        // CODEGEN: 操作 getForexRmbRate 以后生成的消息协定不是 RPC，也不是换行文档。
        [System.ServiceModel.OperationContractAttribute(Action="http://webxml.com.cn/ForexRmbRateWebServiceHttpGet/getForexRmbRateRequest", ReplyAction="http://webxml.com.cn/ForexRmbRateWebServiceHttpGet/getForexRmbRateResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        Toyz4net.Core.ForexRmbRateWebService.getForexRmbRateResponse getForexRmbRate(Toyz4net.Core.ForexRmbRateWebService.getForexRmbRateRequest request);
        
        // CODEGEN: 操作 getForexRmbRatePro 以后生成的消息协定不是 RPC，也不是换行文档。
        [System.ServiceModel.OperationContractAttribute(Action="http://webxml.com.cn/ForexRmbRateWebServiceHttpGet/getForexRmbRateProRequest", ReplyAction="http://webxml.com.cn/ForexRmbRateWebServiceHttpGet/getForexRmbRateProResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        Toyz4net.Core.ForexRmbRateWebService.getForexRmbRateProResponse getForexRmbRatePro(Toyz4net.Core.ForexRmbRateWebService.getForexRmbRateProRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getForexRmbRateRequest {
        
        public getForexRmbRateRequest() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getForexRmbRateResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://webxml.com.cn/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Data.DataSet DataSet;
        
        public getForexRmbRateResponse() {
        }
        
        public getForexRmbRateResponse(System.Data.DataSet DataSet) {
            this.DataSet = DataSet;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getForexRmbRateProRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string theUserID;
        
        public getForexRmbRateProRequest() {
        }
        
        public getForexRmbRateProRequest(string theUserID) {
            this.theUserID = theUserID;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getForexRmbRateProResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://webxml.com.cn/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Data.DataSet DataSet;
        
        public getForexRmbRateProResponse() {
        }
        
        public getForexRmbRateProResponse(System.Data.DataSet DataSet) {
            this.DataSet = DataSet;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    public interface ForexRmbRateWebServiceHttpGetChannel : Toyz4net.Core.ForexRmbRateWebService.ForexRmbRateWebServiceHttpGet, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    public partial class ForexRmbRateWebServiceHttpGetClient : System.ServiceModel.ClientBase<Toyz4net.Core.ForexRmbRateWebService.ForexRmbRateWebServiceHttpGet>, Toyz4net.Core.ForexRmbRateWebService.ForexRmbRateWebServiceHttpGet {
        
        public ForexRmbRateWebServiceHttpGetClient() {
        }
        
        public ForexRmbRateWebServiceHttpGetClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ForexRmbRateWebServiceHttpGetClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ForexRmbRateWebServiceHttpGetClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ForexRmbRateWebServiceHttpGetClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Toyz4net.Core.ForexRmbRateWebService.getForexRmbRateResponse Toyz4net.Core.ForexRmbRateWebService.ForexRmbRateWebServiceHttpGet.getForexRmbRate(Toyz4net.Core.ForexRmbRateWebService.getForexRmbRateRequest request) {
            return base.Channel.getForexRmbRate(request);
        }
        
        public System.Data.DataSet getForexRmbRate() {
            Toyz4net.Core.ForexRmbRateWebService.getForexRmbRateRequest inValue = new Toyz4net.Core.ForexRmbRateWebService.getForexRmbRateRequest();
            Toyz4net.Core.ForexRmbRateWebService.getForexRmbRateResponse retVal = ((Toyz4net.Core.ForexRmbRateWebService.ForexRmbRateWebServiceHttpGet)(this)).getForexRmbRate(inValue);
            return retVal.DataSet;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Toyz4net.Core.ForexRmbRateWebService.getForexRmbRateProResponse Toyz4net.Core.ForexRmbRateWebService.ForexRmbRateWebServiceHttpGet.getForexRmbRatePro(Toyz4net.Core.ForexRmbRateWebService.getForexRmbRateProRequest request) {
            return base.Channel.getForexRmbRatePro(request);
        }
        
        public System.Data.DataSet getForexRmbRatePro(string theUserID) {
            Toyz4net.Core.ForexRmbRateWebService.getForexRmbRateProRequest inValue = new Toyz4net.Core.ForexRmbRateWebService.getForexRmbRateProRequest();
            inValue.theUserID = theUserID;
            Toyz4net.Core.ForexRmbRateWebService.getForexRmbRateProResponse retVal = ((Toyz4net.Core.ForexRmbRateWebService.ForexRmbRateWebServiceHttpGet)(this)).getForexRmbRatePro(inValue);
            return retVal.DataSet;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://webxml.com.cn/", ConfigurationName="ForexRmbRateWebService.ForexRmbRateWebServiceHttpPost")]
    public interface ForexRmbRateWebServiceHttpPost {
        
        // CODEGEN: 操作 getForexRmbRate 以后生成的消息协定不是 RPC，也不是换行文档。
        [System.ServiceModel.OperationContractAttribute(Action="http://webxml.com.cn/ForexRmbRateWebServiceHttpPost/getForexRmbRateRequest", ReplyAction="http://webxml.com.cn/ForexRmbRateWebServiceHttpPost/getForexRmbRateResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        Toyz4net.Core.ForexRmbRateWebService.getForexRmbRateResponse1 getForexRmbRate(Toyz4net.Core.ForexRmbRateWebService.getForexRmbRateRequest1 request);
        
        // CODEGEN: 操作 getForexRmbRatePro 以后生成的消息协定不是 RPC，也不是换行文档。
        [System.ServiceModel.OperationContractAttribute(Action="http://webxml.com.cn/ForexRmbRateWebServiceHttpPost/getForexRmbRateProRequest", ReplyAction="http://webxml.com.cn/ForexRmbRateWebServiceHttpPost/getForexRmbRateProResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        Toyz4net.Core.ForexRmbRateWebService.getForexRmbRateProResponse1 getForexRmbRatePro(Toyz4net.Core.ForexRmbRateWebService.getForexRmbRateProRequest1 request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getForexRmbRateRequest1 {
        
        public getForexRmbRateRequest1() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getForexRmbRateResponse1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://webxml.com.cn/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Data.DataSet DataSet;
        
        public getForexRmbRateResponse1() {
        }
        
        public getForexRmbRateResponse1(System.Data.DataSet DataSet) {
            this.DataSet = DataSet;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getForexRmbRateProRequest1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string theUserID;
        
        public getForexRmbRateProRequest1() {
        }
        
        public getForexRmbRateProRequest1(string theUserID) {
            this.theUserID = theUserID;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getForexRmbRateProResponse1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://webxml.com.cn/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Data.DataSet DataSet;
        
        public getForexRmbRateProResponse1() {
        }
        
        public getForexRmbRateProResponse1(System.Data.DataSet DataSet) {
            this.DataSet = DataSet;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    public interface ForexRmbRateWebServiceHttpPostChannel : Toyz4net.Core.ForexRmbRateWebService.ForexRmbRateWebServiceHttpPost, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    public partial class ForexRmbRateWebServiceHttpPostClient : System.ServiceModel.ClientBase<Toyz4net.Core.ForexRmbRateWebService.ForexRmbRateWebServiceHttpPost>, Toyz4net.Core.ForexRmbRateWebService.ForexRmbRateWebServiceHttpPost {
        
        public ForexRmbRateWebServiceHttpPostClient() {
        }
        
        public ForexRmbRateWebServiceHttpPostClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ForexRmbRateWebServiceHttpPostClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ForexRmbRateWebServiceHttpPostClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ForexRmbRateWebServiceHttpPostClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Toyz4net.Core.ForexRmbRateWebService.getForexRmbRateResponse1 Toyz4net.Core.ForexRmbRateWebService.ForexRmbRateWebServiceHttpPost.getForexRmbRate(Toyz4net.Core.ForexRmbRateWebService.getForexRmbRateRequest1 request) {
            return base.Channel.getForexRmbRate(request);
        }
        
        public System.Data.DataSet getForexRmbRate() {
            Toyz4net.Core.ForexRmbRateWebService.getForexRmbRateRequest1 inValue = new Toyz4net.Core.ForexRmbRateWebService.getForexRmbRateRequest1();
            Toyz4net.Core.ForexRmbRateWebService.getForexRmbRateResponse1 retVal = ((Toyz4net.Core.ForexRmbRateWebService.ForexRmbRateWebServiceHttpPost)(this)).getForexRmbRate(inValue);
            return retVal.DataSet;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Toyz4net.Core.ForexRmbRateWebService.getForexRmbRateProResponse1 Toyz4net.Core.ForexRmbRateWebService.ForexRmbRateWebServiceHttpPost.getForexRmbRatePro(Toyz4net.Core.ForexRmbRateWebService.getForexRmbRateProRequest1 request) {
            return base.Channel.getForexRmbRatePro(request);
        }
        
        public System.Data.DataSet getForexRmbRatePro(string theUserID) {
            Toyz4net.Core.ForexRmbRateWebService.getForexRmbRateProRequest1 inValue = new Toyz4net.Core.ForexRmbRateWebService.getForexRmbRateProRequest1();
            inValue.theUserID = theUserID;
            Toyz4net.Core.ForexRmbRateWebService.getForexRmbRateProResponse1 retVal = ((Toyz4net.Core.ForexRmbRateWebService.ForexRmbRateWebServiceHttpPost)(this)).getForexRmbRatePro(inValue);
            return retVal.DataSet;
        }
    }
}
